### ISSUE TITLE
I don’t know why the cell becomes a horizontal line

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/jupyterlab#10998]
![image](https://user-images.githubusercontent.com/39434627/131984237-b927d62a-5ca5-4468-8eaf-62b9077804bd.png)

As shown in the picture, I don’t know why the code in the cell is gone, and it has become a line. Since I upgraded to 3.1.4 and turned on rtc, I found a lot of bugs

**Comment by krassowski** [comment]
This was fixed in JupyterLab 3.1.10 (https://github.com/jupyterlab/jupyterlab/pull/10898). Could you please upgrade and confirm that the fix works for you?

**Comment by icankeep** [comment]
thank you for your reply. [comment](https://github.com/jupyterlab/jupyterlab/issues/10840#issuecomment-899661421)can solve my problem. I'll upgrade lab to 3.1.10

**Comment by icankeep** [comment]
@krassowski hello, my jupyterlab upgraded to 3.1.10, but it still have the same problem when I opened the previous file. Is this the expected state?

**Comment by krassowski** [comment]
Can you create a reproducible example please, so we can try to re-create this and diagnose the issue?

**Comment by icankeep** [comment]
I don’t know the steps to reproduce, but it can be reproduced by opening this notebook with the lab of 3.1.10



```ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e93a11d0-9c02-4550-812e-b88208da40e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d8bddb3b-e5e6-4820-b522-f32590545333",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1207dcec-fafc-4ef8-b8bd-df50889e13b6",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ff9babe7-0f5e-45fb-98b7-c96cce1497f2",
   "metadata": {},
   "source": [
    "# 特征"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa741a5c-58d2-455d-93e0-bb35712c8f9f",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b0b10f7-97d2-4ed0-abe2-0795edae044d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "779fd2ce-7b4e-42b4-87ea-280a1598f664",
   "metadata": {},
   "source": [
    "# 数据拉取"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e77c90b9-e061-437e-b747-5938b6981472",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58642a3a-ba1f-4f08-a7c0-9355eecbe141",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdb62db1-437d-462b-b993-1c60b04df233",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77936c58-883f-440b-84c7-e34d27e331e7",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ab373a4-47c8-4557-901e-9f0b6136adaf",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0d10ee40-9a5e-45c9-bf70-f9e68826f6a0",
   "metadata": {},
   "source": [
    "# 数据预处理"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f275d75e-9ab4-413d-914b-811d6003e64c",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9bac9859-a0a5-4dfc-876b-2f590ba30cbb",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "002930ab-67f8-4dc8-9d7b-c32ecda8ebb2",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a5dadccd-b3f1-4f2d-8cd9-ea108425b413",
   "metadata": {},
   "source": [
    "# xgb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb43e452-f6dd-4370-8bb4-41332666ba58",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9c248f4-674b-4bf6-b019-53f54b5e03fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f9e3633-59b4-4017-bb42-53b26d56f66e",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb32f18a",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_pickle('./dnn_mob3_data_xgb.pkl')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c6e223df-0478-45c5-bad7-8d3743291f6a",
   "metadata": {
    "tags": []
   },
   "source": [
    "# 训练时模型结构"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5df464e4-d134-4d42-9131-46615252cb4e",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a116667-cc43-4e7b-9b41-f51a94307877",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "59bf278d-f33e-4844-8fc8-23991ac99c22",
   "metadata": {},
   "source": [
    "# 剔除辅助任务"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "46582a77-1296-4a13-ac95-21ac12879b3b",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "697c8842-61c9-403e-bfa1-5e888b57160a",
   "metadata": {},
   "outputs": [],
   "source": [
    "new_model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "18fdcad5-da3f-43d1-a2a9-9b81dd790072",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "11a11b30",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1fd2d92e",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8699504a",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d0d9225",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "87053e25-eebf-4ed9-9464-8a4480e3521b",
   "metadata": {},
   "source": [
    "# pb文件"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16a13ed8-74de-4f23-89cd-4cf60a6d960a",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7bcdf186-20f8-4e73-841a-e2715cf6ac0c",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d69c019-680e-46c1-9b17-8793c37ebc63",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7cc2f31c-8395-40a4-a13f-94c75d205251",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2798f9ee-e6cb-4ab2-98a2-41d1c5af2482",
   "metadata": {
    "tags": []
   },
   "source": [
    "# ks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a75342b0-f313-4ff6-bd9b-31ced0d59b29",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f584a7c-bb66-4b03-a0b1-7ac01c89868d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1a771b33-aab9-4c77-9c00-cc2d71b132dd",
   "metadata": {},
   "source": [
    "# 交叉矩阵"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6c27a03-ff47-48f7-af6e-75ca783d2491",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68e9588e",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "327a3b63-d86b-4607-8cfd-e43fcea9d16f",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3feaf88-ad46-4459-89c6-403c3e55b1c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15c6c60f-371e-42bb-a20a-bc6752417822",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "db033789-4957-4a09-a62c-4dcae00ee47b",
   "metadata": {},
   "source": [
    "# top20"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7669540",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bde9e530",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a5a4254c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "dd2d23ab",
   "metadata": {},
   "source": [
    "# 融合"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e4845f01",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc186cd8",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6f846863",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e46f9ae7-7ce7-4200-ab70-d9ffaff34e88",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8299eea1-d103-4a84-9ca1-5baa3cb286ca",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67eb04bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "13941610",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a9a654d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ea97bcd3",
   "metadata": {},
   "source": [
    "# 特征"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28e2f285",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5da8680",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "29024b44",
   "metadata": {},
   "source": [
    "# 数据拉取"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28b03355",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d1a9bcce",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4d6344bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1b56f1f",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "35b7323b",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bd909e50",
   "metadata": {},
   "source": [
    "# 数据预处理"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cca06018",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d91d2638",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b63ed53",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a7bb1f56",
   "metadata": {},
   "source": [
    "# xgb"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a24dbf4",
   "metadata": {
    "tags": []
   },
   "source": [
    "# 训练时模型结构"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20a6e4fe",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff822904",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4efea718",
   "metadata": {},
   "source": [
    "# 剔除辅助任务"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "60248327",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "22d1660b",
   "metadata": {},
   "outputs": [],
   "source": [
    "new_model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "796cc7fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2798f9ee-e6cb-4ab2-98a2-41d1c5af2482",
   "metadata": {
    "tags": []
   },
   "source": [
    "# ks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a75342b0-f313-4ff6-bd9b-31ced0d59b29",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f584a7c-bb66-4b03-a0b1-7ac01c89868d",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1a771b33-aab9-4c77-9c00-cc2d71b132dd",
   "metadata": {},
   "source": [
    "# 交叉矩阵"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c6c27a03-ff47-48f7-af6e-75ca783d2491",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "327a3b63-d86b-4607-8cfd-e43fcea9d16f",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3feaf88-ad46-4459-89c6-403c3e55b1c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15c6c60f-371e-42bb-a20a-bc6752417822",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "db033789-4957-4a09-a62c-4dcae00ee47b",
   "metadata": {},
   "source": [
    "# top20"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e46f9ae7-7ce7-4200-ab70-d9ffaff34e88",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"a\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8299eea1-d103-4a84-9ca1-5baa3cb286ca",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

```

**Comment by icankeep** [comment]
![image](https://user-images.githubusercontent.com/39434627/132217823-8b53d4b5-9be9-418c-9fe2-544f45d16321.png)


When deleting some cells, these horizontal lines will disappear

**Comment by Mithil467** [comment]
I tried running this locally on the latest master, and can confirm this bug exists.
![image](https://user-images.githubusercontent.com/41439841/133373311-fb8754c4-0d44-4199-8ee3-53d26abfa795.png)

**Comment by Mithil467** [comment]
Hey @icankeep, after further discussion, we have observed that there are cells with non-unique IDs. This is causing exceptions with the rendering of these cells.
Can you help us understand what could have caused this notebook to be malformed? Was it edited manually, or maybe due to some extension or something similar?
It would be awesome if you could directly comment under the issue #10933 for further discussion at a single place!
