### ISSUE TITLE
collaboration and tags

### ISSUE THREAD

**Issue by djangoliv** [jupyterlab/jupyterlab#11038]
## Description

When we share a notebook with tags, the tags are removed.

## Reproduce

0. jupyterlab --collaborative
1. Create a notebook with cell and tags
2. Save it
3. Use jupyterlab-link-share to copy the share link
4. Open the link in private mode (incognito-mode)
5. The file is rewrite without the tags

## Expected behavior

Keep the tags.

## Context

- firefox: 91.0.2 (64 bits)
- JupyterLab 3.1.10

Regards

**Comment by hbcarlos** [comment]
Hi @djangoliv, thanks for opening this issue.

The tags are stored in the cell's metadata, and by default, the metadata is not shared.
This is an ongoing discussion because there are some attributes in the metadata (like `kernelspec`) that we are not sure if should be shared or not.

**Comment by hbcarlos** [comment]
@meeseeksdev tag "Real Time Collaboration"

**Comment by hbcarlos** [comment]
@meeseeksdev tag "tag:Real Time Collaboration"

**Comment by blink1073** [comment]
Oh, so the issue was that the tag name didn't exist, I thought something might have been wrong with our [config](https://github.com/jupyterlab/jupyterlab/blob/66aabb72bf0fc26021868eb0d1a0555ef5b759ac/.meeseeksdev.yml#L5)

**Comment by djangoliv** [comment]
@hbcarlos I would prefer the tags to be shared, but the real problem is removing them from the original file.

**Comment by krassowski** [comment]
From the given the `editable` is a metadata field as well, and some extensions (like citation manager) use metadata for storing information essential for their functioning, I would expect the metadata to be shared. If we do not want specific items of metadata to be shared we can create a blacklist.

**Comment by hbcarlos** [comment]
> Oh, so the issue was that the tag name didn't exist. I thought something might have been wrong with our [config](https://github.com/jupyterlab/jupyterlab/blob/66aabb72bf0fc26021868eb0d1a0555ef5b759ac/.meeseeksdev.yml#L5)

Yes, it was my fault. Thanks!

**Comment by hbcarlos** [comment]
> I would expect the metadata to be shared. If we do not want specific items of metadata to be shared, we can create a blocklist.

Agree. We should, by default, share the metadata and remove the attributes we don't want to share.

**Comment by hbcarlos** [comment]
Fixed in #11064

**Comment by djangoliv** [comment]
@hbcarlos :
With this fix, the created tags are effectively shared, but, the tags that are natively in the notebooks (in the ipynb file) are still not shared. 
Would it be possible to take them into account?

**Comment by hbcarlos** [comment]
Hi @djangoliv, which tags do you mean?

**Comment by djangoliv** [comment]
Hum, I just realized that the problem was only on jupyterhub. In jupyterlab, the tags are present. 
I don't know why it's different under jupyterhub but when I share a notebook in collaboration mode the file tags are not present in the second notebook, whereas if we create a new tag it is present on both sides.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-collaboration-and-tags/11259/3
