### ISSUE TITLE
Server console disappears when starting terminal in browser

### ISSUE THREAD

**Issue by Qrox** [jupyterlab/jupyterlab#11598]
## Description
I usually start jupyter lab server on a remote computer and connect to the server via the local computer. It has been working fine until I recently updated to jupyter lab 3.2.4 from 3.0.12. Now when I start jupyter lab server and start a terminal in the browser, the server console window disappears. I can still connect to the server from my local computer, but I cannot see the server console output because the window is hidden.

## Reproduce

1. Start jupyter lab server with command `jupyter lab --no-browser --ip 0.0.0.0 --port 8888 --certfile foo.pem --keyfile foo.key` (the command is executed as a .bat script)
2. Start a terminal session in the browser (it will start a powershell session)
3. Server console disappears

## Expected behavior

The server console is always shown, unless configured to be hidden.

## Context

- Operating System and version: Windows 10 Professional 20H2
- Browser and version: Chrome 96.0.4664.45
- JupyterLab version: 3.2.4

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        D:\Python39\tensorflow\Scripts
        D:\NVIDIA\CUDA\bin
        D:\NVIDIA\CUDA\extras\CUPTI\lib64
        D:\NVIDIA\CUDA\include
        D:\Python39\tensorflow\Scripts
        D:\Python39\Scripts
        D:\NVIDIA\CUDA\bin
        D:\NVIDIA\CUDA\libnvvp

        D:\Git\mingw64\bin
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Windows\System32\OpenSSH\
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common      
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        D:\GitExtensions\
        E:\matlab\runtime\win64
        E:\matlab\bin
        E:\matlab\polyspace\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.3.0\
        C:\Users\pc15465\AppData\Local\Microsoft\WindowsApps        

sys.path:
        D:\Python39\tensorflow\Scripts\jupyter-troubleshoot.EXE     
        D:\Python39\python39.zip
        D:\Python39\DLLs
        D:\Python39\lib
        D:\Python39
        D:\Python39\tensorflow
        D:\Python39\tensorflow\lib\site-packages
        D:\Python39\tensorflow\lib\site-packages\win32
        D:\Python39\tensorflow\lib\site-packages\win32\lib
        D:\Python39\tensorflow\lib\site-packages\Pythonwin

sys.executable:
        D:\Python39\tensorflow\Scripts\python.exe

sys.version:
        3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.19042-SP0

where jupyter:
        D:\Python39\tensorflow\Scripts\jupyter.exe

pip list:
        Package                      Version
        ---------------------------- ---------
        absl-py                      1.0.0
        anyio                        3.4.0
        argon2-cffi                  21.1.0
        astunparse                   1.6.3
        attr                         0.3.1
        attrs                        21.2.0
        Babel                        2.9.1
        backcall                     0.2.0
        bleach                       4.1.0
        cachetools                   4.2.4
        certifi                      2021.10.8
        cffi                         1.15.0
        charset-normalizer           2.0.8
        cloudpickle                  2.0.0
        colorama                     0.4.4
        cycler                       0.11.0
        debugpy                      1.5.1
        decorator                    5.1.0
        defusedxml                   0.7.1
        dm-tree                      0.1.6
        entrypoints                  0.3
        et-xmlfile                   1.1.0
        flatbuffers                  2.0
        fonttools                    4.28.2
        gast                         0.4.0
        google-auth                  2.3.3
        google-auth-oauthlib         0.4.6
        google-pasta                 0.2.0
        grpcio                       1.42.0
        gviz-api                     1.10.0
        h5py                         3.6.0
        idna                         3.3
        importlib-metadata           4.8.2
        ipykernel                    6.5.1
        ipython                      7.30.0
        ipython-genutils             0.2.0
        ipywidgets                   7.6.5
        jedi                         0.18.1
        Jinja2                       3.0.3
        json5                        0.9.6
        jsonschema                   4.2.1
        jupyter-client               7.1.0
        jupyter-core                 4.9.1
        jupyter-server               1.12.1
        jupyterlab                   3.2.4
        jupyterlab-pygments          0.1.2
        jupyterlab-server            2.8.2
        jupyterlab-widgets           1.0.2
        keras                        2.7.0
        Keras-Preprocessing          1.1.2
        kiwisolver                   1.3.2
        libclang                     12.0.0
        Markdown                     3.3.6
        MarkupSafe                   2.0.1
        matplotlib                   3.5.0
        matplotlib-inline            0.1.3
        mistune                      0.8.4
        nbclassic                    0.3.4
        nbclient                     0.5.9
        nbconvert                    6.3.0
        nbformat                     5.1.3
        nest-asyncio                 1.5.1
        notebook                     6.4.6
        numpy                        1.21.4
        oauthlib                     3.1.1
        openpyxl                     3.0.9
        opt-einsum                   3.3.0
        packaging                    21.3
        pandas                       1.3.4
        pandocfilters                1.5.0
        parso                        0.8.3
        pickleshare                  0.7.5
        Pillow                       8.4.0
        pip                          21.2.4
        prometheus-client            0.12.0
        prompt-toolkit               3.0.23
        protobuf                     3.19.1
        psutil                       5.8.0
        pyasn1                       0.4.8
        pyasn1-modules               0.2.8
        pycparser                    2.21
        Pygments                     2.10.0
        pynvml                       11.0.0
        pyparsing                    3.0.6
        pyrsistent                   0.18.0
        python-dateutil              2.8.2
        pytz                         2021.3
        pywin32                      302
        pywinpty                     1.1.6
        pyzmq                        22.3.0
        requests                     2.26.0
        requests-oauthlib            1.3.0
        rsa                          4.8
        scipy                        1.7.3
        Send2Trash                   1.8.0
        setuptools                   58.1.0
        setuptools-scm               6.3.2
        six                          1.16.0
        sniffio                      1.2.0
        tensorboard                  2.7.0
        tensorboard-data-server      0.6.1
        tensorboard-plugin-profile   2.5.0
        tensorboard-plugin-wit       1.8.0
        tensorflow                   2.7.0
        tensorflow-estimator         2.7.0
        tensorflow-io-gcs-filesystem 0.22.0
        tensorflow-probability       0.15.0
        termcolor                    1.1.0
        terminado                    0.12.1
        testpath                     0.5.0
        tomli                        1.2.2
        tornado                      6.1
        traitlets                    5.1.1
        typing_extensions            4.0.1
        urllib3                      1.26.7
        wcwidth                      0.2.5
        webencodings                 0.5.1
        websocket-client             1.2.1
        Werkzeug                     2.0.2
        wheel                        0.37.0
        widgetsnbextension           3.5.2
        wrapt                        1.13.3
        zipp                         3.6.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2021-12-01 20:29:55.092 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-12-01 20:29:55.100 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-12-01 20:29:55.371 ServerApp] nbclassic | extension was successfully linked.
[I 2021-12-01 20:29:55.416 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-12-01 20:29:55.419 LabApp] JupyterLab extension loaded from D:\Python39\tensorflow\lib\site-packages\jupyterlab
[I 2021-12-01 20:29:55.419 LabApp] JupyterLab application directory is D:\Python39\tensorflow\share\jupyter\lab
[I 2021-12-01 20:29:55.428 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-12-01 20:29:55.429 ServerApp] Serving notebooks from local directory: E:\GitRepos
[I 2021-12-01 20:29:55.429 ServerApp] Jupyter Server 1.12.1 is running at:
[I 2021-12-01 20:29:55.429 ServerApp] https://*snip*/lab
[I 2021-12-01 20:29:55.429 ServerApp]  or https://127.0.0.1:8888/lab
[I 2021-12-01 20:29:55.429 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2 $ref: keywords ignored in schema at path "#/properties/codeCellConfig"
e @ 1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2
1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2 $ref: keywords ignored in schema at path "#/properties/markdownCellConfig"
e @ 1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2
1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2 $ref: keywords ignored in schema at path "#/properties/rawCellConfig"
e @ 1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2
1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2 $ref: keywords ignored in schema at path "#/properties/codeCellConfig"
e @ 1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2
1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2 $ref: keywords ignored in schema at path "#/properties/markdownCellConfig"
e @ 1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2
1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2 $ref: keywords ignored in schema at path "#/properties/rawCellConfig"
e @ 1902.84e773fc133a804e6fdf.js?v=84e773fc133a804e6fdf:2
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/main.eb1a25439b8fda26a7d5.js.map?v=eb1a25439b8fda26a7d5: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/4155.784ca1752696680bf373.js.map?v=784ca1752696680bf373: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/2719.53d253f455777717e852.js.map?v=53d253f455777717e852: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/6700.9bfbe77418dd01d623dd.js.map?v=9bfbe77418dd01d623dd: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/807.0b3631971a2309dbdd33.js.map?v=0b3631971a2309dbdd33: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/7294.46e9d2dfa68082780e97.js.map?v=46e9d2dfa68082780e97: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/3935.e00facce2e55a4af6e62.js.map?v=e00facce2e55a4af6e62: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/7616.4b95a64db517ac4a41db.js.map?v=4b95a64db517ac4a41db: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/9761.bef05a557014845a6440.js.map?v=bef05a557014845a6440: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/1057.82f46c506f470017d985.js.map?v=82f46c506f470017d985: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/4429.9d0e9af89b4ab5bf2a29.js.map?v=9d0e9af89b4ab5bf2a29: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/4151.b6bc0f898c884a0d860c.js.map?v=b6bc0f898c884a0d860c: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/1902.84e773fc133a804e6fdf.js.map?v=84e773fc133a804e6fdf: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/911.0c08f040896753efc653.js.map?v=0c08f040896753efc653: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/126.f4d6c5dd481bf984b48c.js.map?v=f4d6c5dd481bf984b48c: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/7796.fe18ad4c91328bf475cb.js.map?v=fe18ad4c91328bf475cb: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/4570.44c948d7eae0f307f23c.js.map?v=44c948d7eae0f307f23c: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/1036.b9f46dde7c355b633d3b.js.map?v=b9f46dde7c355b633d3b: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/7084.8cbd74268350b25b03e6.js.map?v=8cbd74268350b25b03e6: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/3029.b0adf5f39eaa4255e1e4.js.map?v=b0adf5f39eaa4255e1e4: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/5450.15e2f48f754b33d59d30.js.map?v=15e2f48f754b33d59d30: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/3123.98d18492499b148722e5.js.map?v=98d18492499b148722e5: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/4631.96a143e70f005fef7b59.js.map?v=96a143e70f005fef7b59: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/3502.aeb1c9a266248b03d3f5.js.map?v=aeb1c9a266248b03d3f5: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/714.d38baae8faccca175d4b.js.map?v=d38baae8faccca175d4b: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/jlab_core.8254cd1e48acf4f1b11e.js.map?v=8254cd1e48acf4f1b11e: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/9473.f6adb1fcd9ac2f6ab565.js.map?v=f6adb1fcd9ac2f6ab565: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/1033.fc4792a37de5b414eb76.js.map?v=fc4792a37de5b414eb76: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/7755.d506a1d9dadf30b1e490.js.map?v=d506a1d9dadf30b1e490: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://*snip*/static/lab/3496.255652f34e2420a95a8d.js.map?v=255652f34e2420a95a8d: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
</pre>
</details>

**Comment by Qrox** [comment]
Might be related: when I start jupyter lab server locally (with shell script) and start a terminal session in the browser, the server terminal outputs the following error:

```
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
```

**Comment by 3coins** [comment]
Can confirm that similar behavior on Mac OS, if a terminal is open and browser refreshed. Note, that opening a new terminal from launcher works fine.


![jlab-terminal-freeze](https://user-images.githubusercontent.com/289369/144922624-ca211e19-3c10-4da2-9856-08a078923b6d.gif)


Server app is not currently capturing where this error is exactly happening, so adding better logging around this will be helpful too. This is the only debug message provided.
```sh
TermSocket.open: 1
not able to serialize: expected string or bytes-like object
TermSocket.open: Opened 1
```

**Comment by davidbrochart** [comment]
@3coins I can see a similar behavior, but only on Firefox: refreshing the window presents you with a blinking cursor in the terminal, but you just need to hit Enter to get your terminal back. Is it the case also on your side?
See also https://github.com/jupyterlab/retrolab/issues/298

**Comment by 3coins** [comment]
@davidbrochart You are right about hitting enter to get the terminal, but I see this issue on Chrome as well. In-fact, you get the terminal at any resize, e.g., when I opened or closed the file browser tab, I got the terminal back. Here are my browser versions:

**Chrome**
Version 96.0.4664.55 (Official Build) (x86_64)

**Firefox**
91.3.0esr (64-bit)

**Comment by davidbrochart** [comment]
Interesting, I don't see the behavior with Chrome, only with Firefox. It might be hard to reproduce, as it could be related to Windows and I don't have a Windows machine.

**Comment by 3coins** [comment]
This was on a Mac, Big Sur.

**Comment by davidbrochart** [comment]
Ah, I have a Linux machine anyway.

**Comment by zer0-memory** [comment]
> @3coins I can see a similar behavior, but only on Firefox: refreshing the window presents you with a blinking cursor in the terminal, but you just need to hit Enter to get your terminal back. Is it the case also on your side? See also [jupyterlab/retrolab#298](https://github.com/jupyterlab/retrolab/issues/298)

I think a solution to #10633 would solve all of these

**Comment by fcollonval** [comment]
The refresh behavior seen on reload is fixed in terminado 0.13.0.

@Qrox your issue does not seem related. But could you try the latest version of terminado?

To update run either `pip install -U terminado` or `conda install "terminado>=0.13.0"`

**Comment by Qrox** [comment]
@fcollonval I updated terminado to 0.13.1 and the issue persists.

**Comment by cupdike** [comment]
Ctrl-C FTW... 
![WonkyJupyterLabTerminal](https://github.com/jupyterlab/jupyterlab/assets/133214/f036f583-e4b1-497d-afc0-435c459f49e7)
