### ISSUE TITLE
Markdown cells break notebook trust

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#12889]
## Description
When I rsync a notebook (which contains atleast 1 markdown cell) from another host to my host, the notebook is not trusted by default which is expected since the signature wouldn't exist on my machine by default. 

But when I run `Trust Notebook` from the Command Palette, it trusts the notebook temporarily but when closing and reopening the notebook, the trust doesn't not persist and I have to re-trust the notebook. 

Investigating this, I found that this is caused because in the `NotebookActions.trust` function, we set `trusted: true` in all cells but only pop it out of code cells when computing signature. Hence, when computing the signature through the `Trust Notebook` command it adds an additional key to the signature which is not present when we write a notebook to disk and hence trust doesn't persist.

Relevant code refs - 
- `NotebookActions.trust`- https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook/src/actions.tsx#L2024
- `_check_cells` - https://github.com/jupyter/nbformat/blob/f712d60f13c5b168313222cbf4bee7face98a081/nbformat/sign.py#L499

## Reproduce

1. To simulate the rsync, we can delete the signature of any notebook (with 1 markdown cell) from the `~/.local/share/jupter/nbsignatures.db`.
2. Now, opening the notebook will show as untrusted (expected)
3. Run `Trust Notebook` from the Command Palette.
4. Close notebook
5. Reopen notebook

## Expected behavior
The trust should persist when reopening the notebook

## Context

- Operating System and version: Linux
- Browser and version: Chrome 103
- JupyterLab version: 3.4.3

**Comment by divyansshhh** [comment]
I can raise a PR to fix this but I have some questions -
1. Is there a reason for trusting all cell? If not, I can fix it here.
2. If there is a usecase for trusting all cells, we can fix this in nbformat.

**Comment by mlucool** [comment]
CC @Carreau

**Comment by jweill-aws** [comment]
@davidbrochart has a PR that may be related: https://github.com/jupyterlab/jupyterlab/pull/12756

There is also an issue involving blank cells and notebook trust: https://github.com/jupyterlab/jupyterlab/issues/9765 (thanks @krassowski).

**Comment by Carreau** [comment]
I merged a few hours a go a change in nbformat that will be much more verbose and unhappy if given an invalid notebook. I'll try to make a beta release soon but I want to make sure I do it properly as nbformat apparently is also on npm.

Note that right now nbformat automatically try to fix notebooks, which leads to those trust issues. 

The new version will complain with warnings, and in a few minor version it will fail as this is a security concern.

If you are on a dev version of JupyterLab please try with the main branch of nbformat, that should help you to detect when invalid notebook are sent from the frontend.

**Comment by divyansshhh** [comment]
I don't have a dev version at hand. I'll try to set it up and check.

**Comment by krassowski** [comment]
I can still reproduce the original issue. We have two possible solutions:
- a) remove `trusted` metadata from non-code cells before serialisation on JupyterLab side
- b) modify nbformat to allow non-code cells to be trusted (and always remove `trusted` from signature)
    - it would require a new nbformat version
    - this would enable us to allow unconstrained HTML in Markdown cells
         > use case: a user wants to take advantage of a new HTML/CSS feature but it was not yet added to allow list of the sanitizer; with trust affecting Markdown cells they can just trust the Markdown cell rather than waiting for a new Jupyter app release
    - a counterpoint could be made that if we were to go this road with nbformat, we possibly should consider a more granular trust (e.g. user may want to trust all CSS and HTML but not JS); in a general case of potential future new cells types this could lead to something like `trust: ['text/markdown', 'text/html', 'text/my-custom-language']`

Thoughts?

**Comment by Carreau** [comment]
I'll vote for a.

b) has long been discussed and not allowing arbitrary html in markdown was done on purpose for security reasons.
