### ISSUE TITLE
Reset the `next` npm tag for `@jupyterlab/rendermime-interfaces`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14335]
### Problem

Currently downstreams using the `@jupyterlab/buildutils/lib/update-dependency.js` script to update the `@jupyterlab` packages pull version [4.0.0-alpha.9](https://www.npmjs.com/package/@jupyterlab/rendermime-interfaces/v/4.0.0-alpha.9) because it is marked as `next`.

However the version was unbumped to `3.8.x` for JupyterLab 4: [3.8.0-beta.1](https://www.npmjs.com/package/@jupyterlab/rendermime-interfaces/v/3.8.0-beta.1) to avoid forcing mimerender extension to update their extensions for JupyterLab 4.

![image](https://user-images.githubusercontent.com/591645/230611130-6bf350cb-e1af-426f-bb00-8309f78252ee.png)

### Proposed Solution

We should reset the `next` tag to point to the `3.8.x` version so it's easier to update the packages during the beta and rc cycles.

### Additional context

This usually comes up when updating Notebook 7 to the latest JupyterLab 4 pre-releases: https://github.com/jupyter/notebook

**Comment by jtpio** [comment]
Actually not sure if resetting the tag (for example manually) would help, or if JupyterLab will make it point to `4.0.0-alpha.9` anyway during the release process. Probably the answer is in the release scripts.

**Comment by jtpio** [comment]
Looks like it's back to pointing to `4.0.0-alpha.9`:

![image](https://user-images.githubusercontent.com/591645/234924597-34fb797d-1698-43ec-8180-f946f7d234fd.png)

Maybe we'll have to update the deploy scripts in JupyterLab to add a special case for this package.

**Comment by fcollonval** [comment]
Thanks for checking out @jtpio

**Comment by jtpio** [comment]
Bumping to `4.0.x` to check that again after the final 4.0 release.

**Comment by hbcarlos** [comment]
Hi! I think we have a small problem with this package.

I just created an extension for jupyterlab v3 from the cookiecutter. I tried to install it before changing anything, and it failed.
```
yarn run v1.21.1
$ jlpm build:lib && jlpm build:labextension:dev
$ tsc --sourceMap
node_modules/@jupyterlab/rendermime/lib/widgets.d.ts:8:31 - error TS2420: Class 'RenderedCommon' incorrectly implements interface 'IRenderer'.
  The types of 'title.owner.layout' are incompatible between these types.
    Type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@lumino/widgets/types/layout").Layout | null' is not assignable to type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout | null'.
      Type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@lumino/widgets/types/layout").Layout' is not assignable to type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.
        Property '[Symbol.iterator]' is missing in type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@lumino/widgets/types/layout").Layout' but required in type 'import("/home/carlos/Documents/blockly-widgets/jupyterlab_blockly_widgets/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.

8 export declare abstract class RenderedCommon extends Widget implements IRenderMime.IRenderer {
                                ~~~~~~~~~~~~~~

  node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout.d.ts:83:14
    83     abstract [Symbol.iterator](): IterableIterator<Widget>;
                    ~~~~~~~~~~~~~~~~~
    '[Symbol.iterator]' is declared here.
```

The problem is that we updated the dependencies of `@jupyterlab/rendermime-interfaces` to lumino v2 and released it as a minor version (v3.8.0). When creating a new extension for jupyterlab v3 it installs  `@jupyterlab/rendermime-interfaces` v3.8.0 with lumino v2.

We should bump the version of the packages to 4 or maybe allow both versions of Lumino.

**Comment by echarles** [comment]
I opened https://github.com/jupyterlab/jupyterlab/issues/13647 some time ago for exactly this.

**Comment by jhgoebbert** [comment]
Also `@jupyterlab/docregistry` version 3.6.3 is infected by the bug - and so are many other @lumino 1.x extensions:
https://github.com/jupyterlab/jupyterlab/blob/v3.6.3/packages/docregistry/package.json#L52

**Comment by jtpio** [comment]
Could switching to use the `~` specifier instead of `^` help mitigate this issue (`"@jupyterlab/rendermime-interfaces": "~3.6.3"`) ? This would then require a new JupyterLab 3.6.x release.

**Comment by jhgoebbert** [comment]
Yes, a new JupyerLab 3.6.4 which fixes its `package.json` files could be a solution.
.
In the long run it would be even better if a version 4.0.0 of @jupyterlab/rendermime-interfaces would exist and 3.8.0 could be yanked. But there might be other reasons why that is no option. 🤔

**Comment by krassowski** [comment]
Just FYI, 3.6.4 was released but it did not include the fix yet. THere is a PR here https://github.com/jupyterlab/jupyterlab/pull/14618 and would need to go in 3.6.5.

Note: this also affects CI of nbdime.

**Comment by fcollonval** [comment]
4.0.2 has been released and it should fix this (rendermime-interfaces 3.8.2 supports both lumino 1.x and 2.x)

Could some of you please confirm it fixes your issue?

**Comment by jhgoebbert** [comment]
I tried to build the dask-labextension https://github.com/dask/dask-labextension but unfortunately it still fails with
```
      node_modules/@jupyterlab/rendermime/lib/widgets.d.ts(8,31): error TS2420: Class 'RenderedCommon' incorrectly implements interface 'IRenderer'.
        The types of 'title.owner.layout' are incompatible between these types.
          Type 'import("/dev/shm/dask_labextension-6.1.0/node_modules/@lumino/widgets/types/layout").Layout' is not assignable to type 'import("/dev/shm/dask_labextension-6.1.0/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.
            Property '[Symbol.iterator]' is missing in type 'import("/dev/shm/dask_labextension-6.1.0/node_modules/@lumino/widgets/types/layout").Layout' but required in type 'import("/dev/shm/dask_labextension-6.1.0/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.
```
I double checked if rendermime-interface 3.8.2 is really used and checked `/dev/shm/dask_labextension-6.1.0/node_modules/@jupyterlab/rendermime-interfaces/package.json` but it shows `"version": "3.8.2",´.

**Comment by krassowski** [comment]
It works for me; the previously [failing](https://github.com/krassowski/nbdime/actions/runs/5171102137/attempts/1) CI build of nbdime, is now [passing](https://github.com/krassowski/nbdime/actions/runs/5171102137/attempts/2) smoothly.

Locally a clean install after removing all `node_modules` (and any resolution pins for `rendermime-interface` package if you had any) works fine too (just upgrading `rendermime-interface` may not give you the right versions of other packages I think).

**Comment by jhgoebbert** [comment]
I tried to build the dask-labextension https://github.com/dask/dask-labextension for JupyterLab 3.6.5 but unfortunately it still fails 
```
      node_modules/@jupyterlab/rendermime/lib/widgets.d.ts(8,31): error TS2420: Class 'RenderedCommon' incorrectly implements interface 'IRenderer'.
        The types of 'title.owner.layout' are incompatible between these types.
          Type 'import("dask_labextension-6.1.0/node_modules/@lumino/widgets/types/layout").Layout' is not assignable to type 'import("dask_labextension-6.1.0/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.
            Property '[Symbol.iterator]' is missing in type 'import("dask_labextension-6.1.0/node_modules/@lumino/widgets/types/layout").Layout' but required in type 'import("dask_labextension-6.1.0/node_modules/@jupyterlab/rendermime-interfaces/node_modules/@lumino/widgets/types/layout").Layout'.
```

**Comment by fcollonval** [comment]
@jhgoebbert I solved the issue using the following command within a fresh environment on the [main branch](https://github.com/dask/dask-labextension/commit/46ad95810ddd947c9fd8f16534835b6a5e32f36d):

```bash
# Installation on the current working lock file
jlpm install

# Upgrade to latest 3.x packages
jlpm upgrade --caret --scope jupyterlab

# Minimize dependency versions
jlpm add -D yarn-deduplicate@^5.0.0
jlpm yarn-deduplicate -s fewer
jlpm install

# Should succeed
jlpm build
```

**Comment by fcollonval** [comment]
Not really, it is a choice of the package manager (here yarn) to resolve the constraints: 
- @lumino/widgets@^1.17.0
- @lumino/widgets@^1.37.2
- @lumino/widgets@^1.37.2 || ^2.1.1

By installing the version 1.37.2 and 2.2.0 when actually 1.37.2 could resolve all of them (what would happen with pip or conda for example) - this is the pain of JavaScript packaging. 

This is usually solved by working on reducing duplication with tool like `yarn-deduplicate` or by using package manager options; namely [resolutions](https://yarnpkg.com/configuration/manifest/#resolutions) for yarn and [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) for npm.

**Comment by jhgoebbert** [comment]
Thank you, I think I understand now.

That makes things really difficult for everyone who provides extensions through PyPI as they do not know how the local package manager will handle this. 🤔 
Could that be handled inside of `jupyter_packaging->install_npm()` as it is called from `setup.py` anyway:
( e.g. https://github.com/dask/dask-labextension/blob/main/setup.py#L65 )

**Comment by jtpio** [comment]
There seems to be another issue with the `@jupyterlab/rendermime-interfaces`.

The current `main` (targeting JupyterLab 4.1) defines the following version:

https://github.com/jupyterlab/jupyterlab/blob/0b33a5ca9318d909233914adb0cbd90d3bc7a472/packages/rendermime-interfaces/package.json#L3

While the `4.0.x` defines this version:

https://github.com/jupyterlab/jupyterlab/blob/14705251b7bd90f715a454c568e54655a63a19b4/packages/rendermime-interfaces/package.json#L3

So `4.0.x` is "ahead" of `main`, which can be quite confusing and can also cause issues downstream when using the `4.1` packages, as noticed in https://github.com/jupyter/notebook/pull/7096. Specifying `^3.8.3-alpha.1` or `~3.8.3-alpha.1` resolves to `3.8.6`, but this creates incompatibility probably due to https://github.com/jupyterlab/jupyterlab/pull/15142 which updated some of the lumino dependencies.

Should the version of `@jupyterlab/rendermime-interfaces` on `main` be bumped to `3.9.0-alpha.1`?

**Comment by jtpio** [comment]
Also if we don't manually bump the version of the packages, it will likely create a conflict when releasing JupyterLab 4.1.3 as it would bump to `3.8.6`.

**Comment by jtpio** [comment]
This caused some issues with the new npm 11 when releasing `4.6.0a0`: https://github.com/jupyterlab/jupyterlab/actions/runs/20241725581/job/58111348446#logs, in the `after-publish-assets` step:

```
> npm dist-tag add @jupyterlab/rendermime-interfaces@4.0.0-alpha.9 next
npm error code E401
npm error 401 Unauthorized - PUT https://registry.npmjs.org/-/package/@jupyterlab%2frendermime-interfaces/dist-tags/next
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-12-15T18_00_40_325Z-debug-0.log
Status: 1
stdout: undefined
stderr: undefined
Uncaught exception Error: Command failed: npm dist-tag add @jupyterlab/rendermime-interfaces@4.0.0-alpha.9 next
    at genericNodeError (node:internal/errors:985:15)
    at wrappedFn (node:internal/errors:539:14)
    at checkExecSyncError (node:child_process:925:11)
    at Object.execSync (node:child_process:997:15)
    at Object.run (/home/runner/work/jupyterlab/jupyterlab/.jupyter_releaser_checkout/buildutils/lib/utils.js:267:43)
    at /home/runner/work/jupyterlab/jupyterlab/.jupyter_releaser_checkout/buildutils/lib/publish.js:98:27
    at Array.forEach (<anonymous>)
    at /home/runner/work/jupyterlab/jupyterlab/.jupyter_releaser_checkout/buildutils/lib/publish.js:96:21
    at Array.forEach (<anonymous>)
    at Command.<anonymous> (/home/runner/work/jupyterlab/jupyterlab/.jupyter_releaser_checkout/buildutils/lib/publish.js:95:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8823,
  stdout: null,
  stderr: null
}
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.12/x64/bin/jupyter-releaser", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.12/x64/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.12/x64/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/cli.py", line 139, in invoke
    util.run(hook)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'npm run after:publish:assets' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/finalize_release.py", line 15, in <module>
    run_action("jupyter-releaser publish-assets")
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/common.py", line 25, in run_action
    _run(target, *args, **kwargs)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 94, in run
    raise e
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 86, in run
    process = tee(cmd, **kwargs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser publish-assets' returned non-zero exit status 1.
```
