### ISSUE TITLE
Windows / Chrome: markdown code blocks get corrupted after pasting Windows line endings

### ISSUE THREAD

**Issue by bh1428** [jupyterlab/jupyterlab#14752]
## Description

When you paste text with Windows line endings (`\r\n`) in a code block within a Markdown cell the result is unexpected. Linux line endings (`\n`) work fine, but for Windows line endings the cell content becomes corrupt (although it may seem correct in edit mode). See attached screen capture for a demonstration.

The example is for Python code but this actually does not matter: when another (e.g. xml) or no syntax is specified the issue occurs as well.

Note (edit 2023-12-18): the first part of the reproduction `.mp4` does not play correctly in Chrome (anymore). If you download it (or use Firefox) you still watch it entirely...

https://github.com/jupyterlab/jupyterlab/assets/9745514/df6fdbb4-7482-4802-85a1-701e8b49b176

## Reproduce

1. Open a new Python Notebook.
2. Create a Markdown type cell with a Python codeblock:
    \`\`\`python
    
    \`\`\`
4. Paste some Python code with Windows line endings (`\r\n`) in the codeblock.
5. Run the cell (or save the notebook and reload).

## Expected behavior

When pasting Windows line endings the result should be rendered / saved the same as when pasting Linux line endings.

## Context
  - Issue occurs on Windows 10 and Windows Server 2016; seems not directly operating system related, 
  - Python sys.version: '3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]' but I had the same issue on Python 3.11.3 (also Windows).
  - Issue occurs in JupyterLab >= 4.0.0 not in JupyterLab 3.6.4 or Notebook 6.5.4.
  - Issue occurs in Chrome (114.0.5735.134 normal and incognito mode) not in Firefox (114.0.2)
  - No server and/or JavaScript error message is shown.

<details><summary>Troubleshoot Output</summary>
<pre>
PS E:\projects\markdown> .\venv\Scripts\jupyter.exe troubleshoot
INFO: Could not find files for the given pattern(s).
$PATH:
        C:\Program Files\Python311\Scripts\
        C:\Program Files\Python311\
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Windows\System32\OpenSSH\
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\Microsoft VS Code\bin
        C:\Program Files\TortoiseGit\bin
        C:\Program Files\Git\cmd
        C:\Users\user\.cargo\bin
        C:\Users\user\AppData\Local\Microsoft\WindowsApps

sys.path:
        E:\projects\markdown\venv\Scripts\jupyter-troubleshoot.EXE
        C:\Program Files\Python311\python311.zip
        C:\Program Files\Python311\DLLs
        C:\Program Files\Python311\Lib
        C:\Program Files\Python311
        E:\projects\markdown\venv
        E:\projects\markdown\venv\Lib\site-packages
        E:\projects\markdown\venv\Lib\site-packages\win32
        E:\projects\markdown\venv\Lib\site-packages\win32\lib
        E:\projects\markdown\venv\Lib\site-packages\Pythonwin

sys.executable:
        E:\projects\markdown\venv\Scripts\python.exe

sys.version:
        3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.22621-SP0

pip list:
        Package                  Version
        ------------------------ --------
        anyio                    3.7.0
        argon2-cffi              21.3.0
        argon2-cffi-bindings     21.2.0
        arrow                    1.2.3
        asttokens                2.2.1
        async-lru                2.0.2
        attrs                    23.1.0
        Babel                    2.12.1
        backcall                 0.2.0
        beautifulsoup4           4.12.2
        bleach                   6.0.0
        certifi                  2023.5.7
        cffi                     1.15.1
        charset-normalizer       3.1.0
        colorama                 0.4.6
        comm                     0.1.3
        debugpy                  1.6.7
        decorator                5.1.1
        defusedxml               0.7.1
        executing                1.2.0
        fastjsonschema           2.17.1
        fqdn                     1.5.1
        idna                     3.4
        ipykernel                6.23.3
        ipython                  8.14.0
        ipython-genutils         0.2.0
        isoduration              20.11.0
        jedi                     0.18.2
        Jinja2                   3.1.2
        json5                    0.9.14
        jsonpointer              2.4
        jsonschema               4.17.3
        jupyter_client           8.3.0
        jupyter_core             5.3.1
        jupyter-events           0.6.3
        jupyter-lsp              2.2.0
        jupyter_server           2.6.0
        jupyter_server_terminals 0.4.4
        jupyterlab               4.0.2
        jupyterlab-pygments      0.2.2
        jupyterlab_server        2.23.0
        MarkupSafe               2.1.3
        matplotlib-inline        0.1.6
        mistune                  3.0.1
        nbclassic                1.0.0
        nbclient                 0.8.0
        nbconvert                7.6.0
        nbformat                 5.9.0
        nest-asyncio             1.5.6
        notebook                 6.5.4
        notebook_shim            0.2.3
        overrides                7.3.1
        packaging                23.1
        pandocfilters            1.5.0
        parso                    0.8.3
        pickleshare              0.7.5
        pip                      23.1.2
        platformdirs             3.8.0
        prometheus-client        0.17.0
        prompt-toolkit           3.0.38
        psutil                   5.9.5
        pure-eval                0.2.2
        pycparser                2.21
        Pygments                 2.15.1
        pyrsistent               0.19.3
        python-dateutil          2.8.2
        python-json-logger       2.0.7
        pywin32                  306
        pywinpty                 2.0.10
        PyYAML                   6.0
        pyzmq                    25.1.0
        requests                 2.31.0
        rfc3339-validator        0.1.4
        rfc3986-validator        0.1.1
        Send2Trash               1.8.2
        setuptools               65.5.0
        six                      1.16.0
        sniffio                  1.3.0
        soupsieve                2.4.1
        stack-data               0.6.2
        terminado                0.17.1
        tinycss2                 1.2.1
        tornado                  6.3.2
        traitlets                5.9.0
        typing_extensions        4.6.3
        uri-template             1.3.0
        urllib3                  2.0.3
        wcwidth                  0.2.6
        webcolors                1.13
        webencodings             0.5.1
        websocket-client         1.6.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
PS E:\projects\markdown> .\venv\Scripts\jupyter.exe lab
[I 2023-06-24 13:23:23.484 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-06-24 13:23:23.497 ServerApp] Package jupyter_lsp took 0.0136s to import
[W 2023-06-24 13:23:23.498 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-24 13:23:23.505 ServerApp] Package jupyter_server_terminals took 0.0066s to import
[I 2023-06-24 13:23:23.506 ServerApp] Package nbclassic took 0.0008s to import
[W 2023-06-24 13:23:23.507 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-24 13:23:23.508 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-06-24 13:23:23.508 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-24 13:23:23.508 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-06-24 13:23:23.513 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-06-24 13:23:23.517 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-06-24 13:23:23.521 ServerApp] nbclassic | extension was successfully linked.
[I 2023-06-24 13:23:23.726 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-06-24 13:23:23.892 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-06-24 13:23:23.893 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-06-24 13:23:23.894 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-06-24 13:23:23.895 LabApp] JupyterLab extension loaded from E:\projects\markdown\venv\Lib\site-packages\jupyterlab
[I 2023-06-24 13:23:23.895 LabApp] JupyterLab application directory is E:\projects\markdown\venv\share\jupyter\lab
[I 2023-06-24 13:23:23.896 LabApp] Extension Manager is 'pypi'.
[I 2023-06-24 13:23:23.897 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-06-24 13:23:23.900 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-06-24 13:23:23.901 ServerApp] Serving notebooks from local directory: E:\projects\markdown
[I 2023-06-24 13:23:23.901 ServerApp] Jupyter Server 2.6.0 is running at:
[I 2023-06-24 13:23:23.901 ServerApp] http://localhost:8888/lab?token=88b4fc62dcd2c4f76651b80fe61f557a45ba162f081eda51
[I 2023-06-24 13:23:23.901 ServerApp]     http://127.0.0.1:8888/lab?token=88b4fc62dcd2c4f76651b80fe61f557a45ba162f081eda51
[I 2023-06-24 13:23:23.902 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-06-24 13:23:23.923 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/user/AppData/Roaming/jupyter/runtime/jpserver-384-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=88b4fc62dcd2c4f76651b80fe61f557a45ba162f081eda51
        http://127.0.0.1:8888/lab?token=88b4fc62dcd2c4f76651b80fe61f557a45ba162f081eda51
[I 2023-06-24 13:23:23.954 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2023-06-24 13:23:26.558 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-06-24 13:23:27.173 ServerApp] Kernel started: 5bee51ee-b34b-440e-bbdd-d0f8eb4b774f
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2023-06-24 13:23:28.203 ServerApp] Connecting to kernel 5bee51ee-b34b-440e-bbdd-d0f8eb4b774f.
[I 2023-06-24 13:23:28.210 ServerApp] Connecting to kernel 5bee51ee-b34b-440e-bbdd-d0f8eb4b774f.
[I 2023-06-24 13:23:28.219 ServerApp] Connecting to kernel 5bee51ee-b34b-440e-bbdd-d0f8eb4b774f.
[I 2023-06-24 13:25:27.173 ServerApp] Saving file at /markdown_test.ipynb
[I 2023-06-24 13:31:08.924 ServerApp] Interrupted...
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
</pre>
</details>

**Comment by kuhlaid** [comment]
Thank you [bh1428](https://github.com/bh1428), I have been switching between using JupyterLab in the browser (which is using Linux EOL but VSCode on my Windows desktop is using Windows line endings (which I cannot seem to set in Jupyter notebooks for some reason). If I copy old notebook code from VSCode to a JupyterLab notebook in the browser my markdown gets really messed up in unobvious ways (words being split and moved around). Now that I know this is the problem I will stick with JupyterLab in the browser.

**Comment by JasonWeill** [comment]
To clarify, are you using collaborative mode / real-time collaboration (RTC)? By default, RTC is off in JupyterLab 4.

**Comment by bh1428** [comment]
I noticed the suggestion it might have to do something with https://github.com/jupyterlab/jupyterlab/issues/14715 but in my case I'm not using RTC and I don't have the jupyter-collaboration extension installed:

![2023-06-30 22_31_14-JupyterLab](https://github.com/jupyterlab/jupyterlab/assets/9745514/b0011178-5b2f-42f1-b040-990ca58aba0d)

**Comment by JasonWeill** [comment]
Thanks! We suspect that the issue in #14715 happens whether RTC is enabled or not; your comments on this issue back that up. I appreciate the update.

**Comment by bh1428** [comment]
One other thing I mentioned before (you may have noticed already): I have this issue only in Chrome NOT in Firefox...

**Comment by Nagidrop** [comment]
I have the same problems on Windows 11, JuypterLab Desktop (v4.0.1-1), with similar conditions: RTC off, in code blocks within Markdown cells. I was searching before opening a new issue and found yours. I faced this when typing ` ``` `, copy paste a code snippet into a Markdown cell, press `Enter` to move to next line and type ` ``` ` again to close the code block. Things break right after the "press `Enter`" part.

**Comment by kuhlaid** [comment]
I just noticed this issue using JupyterLab Version 4.0.2 in the Edge browser Version 114 for Windows 11 when working with .ipynb files. I open a notebook in raw editor (not HTML notebook mode), clear out any existing `\r` instances in the raw JSON. I then reopen the notebook in HTML mode and paste in some lines of text from say a VsCode editor or Notebook (which contain `\r\n` line endings) and that corrupts the notebook text. Ideally JupyterLab would simply replace any `\r\n` instances that are pasted into the notebook with `\n` until we can convince Microsoft to stop using `\r\n` line endings. At the very least it would be helpful if JupyterLab would prompt the user with a warning if any `\r\n` begin to appear in the notebook JSON source.

**Comment by krassowski** [comment]
Also reported on discourse: https://discourse.jupyter.org/t/inline-latex-errors/22471

**Comment by JasonWeill** [comment]
As noted in #15492, this is also observed in Edge on Windows.

**Comment by firezym** [comment]
> As noted in #15492, this is also observed in Edge on Windows.

I tested just now on Firefox, it seems fine. The problem appearred on Edge and Brave, which are all chrome based browsers.

**Comment by kiliansinger** [comment]
I just fixed it:
https://github.com/jupyterlab/jupyterlab/pull/15794

**Comment by Irritated851** [comment]
take a look at this information



https://lnkr.fun/7c1317e

**Comment by jonhelfman** [comment]
I updated jupyter lab but I still get corrupted markup using Brave on Windows 10 with 

jupyter_client                8.6.3
jupyter_core                  5.7.2
jupyter-events                0.12.0
jupyter-lsp                   2.2.5
jupyter_server                2.15.0
jupyter_server_terminals      0.5.3
jupyterlab                    4.4.4
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.3

Is it supposed to be fixed now or am I doing something dumb? Thanks
