### ISSUE TITLE
Collapsed cells behave unpredictably when moving with keyboard shortcuts

### ISSUE THREAD

**Issue by jbwhit** [jupyterlab/jupyterlab#15700]
## Description

When selecting a group of cells collapsed under a markdown heading, it appears that they can be moved as a group, but they cannot. Not only that, very strange things happen depending on whether you are moving up or down:
- the cells can appear to disappear completely
- the cells can appear under a different section entirely.

## Reproduce

1. In a notebook, create a markdown section heading cell.
2. Create some number of cells below the section heading.
3. Collapse the section with the arrow beside the heading.
4. Attempt to move the section around with the keyboard shortcut: control+shift+<arrow key> 
5. This will have different behavior depending on the direction and the surrounding cells, I have made a silent 1 minute video showing the various behavior that I see: https://youtu.be/BgTA_ZnELTY 

## Expected behavior

I expected to be able to collapse a section and move the section around with keyboard shortcuts like I can do with an uncollapsed group of cells. 

## Context

- Operating System and version: Mac OS Sonoma 14.2.1
- Browser and version: Firefox 121.0.1 
- JupyterLab version: Version 4.1.0b2 (testing the beta release, but the behavior appears to be the same for older versions).

**Comment by krassowski** [comment]
This appears related to https://github.com/jupyterlab/jupyterlab/issues/10593 and likely would be be solved by https://github.com/jupyterlab/jupyterlab/pull/10631 (which needs more work and then review).

**Comment by krassowski** [comment]
Also, thank you for testing the beta release!

**Comment by JasonWeill** [comment]
I can still reproduce this using the tip of `main` (4.2.0 beta).
