### ISSUE TITLE
Vertical scroll in cell's output view

### ISSUE THREAD

**Issue by asishm** [jupyterlab/jupyterlab#3989]
Currently if I have a dataframe that takes up more vertical space than available (in a cell's output view), it doesn't have a scrollbar. Would be a nice feature to have.

Apologies if this has been posted earlier as well. (My github search skills aren't too strong).

**Comment by jasongrout** [comment]
Right-click on the output, and select "Enable scrolling for Outputs" - you can see a demo in the docs: http://jupyterlab.readthedocs.io/en/stable/user/notebook.html (search for "Enable scrolling").

**Comment by asishm** [comment]
I should clarify that I mean - enable scrolling in the separate tab-based output view.
While I can have scrolling in the notebook and/or sync'd notebooks, it seems there's no scroll option in the output view tab.

Running on Chrome Version 64.0.3282.167 (Official Build) (64-bit) (Windows 10)

![image](https://user-images.githubusercontent.com/1978117/36618307-a4f25b5c-18b8-11e8-8492-51c5a71196d7.png)

**Comment by jasongrout** [comment]
Oh wow, that's definitely a bug. That should automatically have a scrollbar. Thanks for pointing this out.

**Comment by jasongrout** [comment]
This should be a simple CSS fix, adding the overflow attribute to the right div.

**Comment by jasongrout** [comment]
(This might also be impacted by https://github.com/jupyterlab/jupyterlab/pull/3730 - it's probably good to apply that PR first, see if the problem still exists, and then put the fix on top of that PR.)

**Comment by ConorSheehan1** [comment]
Hi @jasongrout I added that overflow attribute in [#4007](https://github.com/jupyterlab/jupyterlab/pull/4007) 
 ![jupyter_lab_scroll_tab_crop](https://user-images.githubusercontent.com/16896053/36646956-a253f31e-1a76-11e8-91d7-ff23347771d6.png) I had a look at [#3730](https://github.com/jupyterlab/jupyterlab/pull/3730) and the option to create a new output view was disabled, but that could've been something I did wrong in setup.
![output-view-disabled_crop](https://user-images.githubusercontent.com/16896053/36646980-d4e796c8-1a76-11e8-883c-9f6f0107dd95.png) Thanks for adding the good first issue tag. As a new dev I really appreciate the opportunity to start small!

**Comment by ibeatty** [comment]
Hi. I'm still seeing this behavior (lack of scrolling for tabs containing an output view) in JupyterLab 0.35.3 (Firefox 63.0.1 on MacOS X 10.14.1). I've updated everything I know how to (`conda update conda` & `conda update --all`)… Am I missing something?

**Comment by nilinykh** [comment]
> Hi. I'm still seeing this behavior (lack of scrolling for tabs containing an output view) in JupyterLab 0.35.3 (Firefox 63.0.1 on MacOS X 10.14.1). I've updated everything I know how to (`conda update conda` & `conda update --all`)… Am I missing something?

same behavior here, no scrolling for tabs with an output view...

**Comment by sharmatime** [comment]
Also seeing the lack of scrolling for tabs containing an output view in JupyterLab 0.35.2

**Comment by jasongrout** [comment]
> Also seeing the lack of scrolling for tabs containing an output view in JupyterLab 0.35.2 in Chrome Version 71.0.3578.98, MaxOSX 10.13.6

I think I've fixed this in #6104.

**Comment by jestemc** [comment]
Still experiencing this in JupyterLab 0.35.4 in Chrome version 75.0.3770.100 in Windows 10.

**Comment by telamonian** [comment]
@jestemc Jlab 1.0.0 was just released. You should try the new version and see if it fixes your problem.

**Comment by jestemc** [comment]
> @jestemc Jlab 1.0.0 was just released. You should try the new version and see if it fixes your problem.
After updating to Jupyter Lab 1.0.2 the output view shows scrollbars correctly.
Thank you!
