### ISSUE TITLE
Syntax coloration for Makefiles

### ISSUE THREAD

**Issue by gsemet** [jupyterlab/jupyterlab#4381]
I love Makefile, even if they do trivial things, at least in my projects I always use the same set of targets.

Can you add a few coloration for Makefile?

thanks !

**Comment by BoPeng** [comment]
JupyterLab uses CodeMirror which, as far as I can tell, [does not support Makefile format](https://codemirror.net/mode/index.html). However, if you can confirm that CMake works fine (View -> Text Color Syntax Highlighting), perhaps you can request using `CMake` as default for `Make`.

**Comment by gsemet** [comment]
Hi. It seems to have been [added in december](https://github.com/codemirror/CodeMirror/pull/5149/files).

**Comment by ian-r-rose** [comment]
Unfortunately, it looks like that PR was never merged.

**Comment by BoPeng** [comment]
@marijnh certainly has some high standard for code inclusion.

Talking about codemirror, @jasongrout , @ian-r-rose  Are you familiar with codemirror? I submitted a PR to codemirror for Python f-string (https://github.com/codemirror/CodeMirror/pull/5338). @marijnh asked me to change something but I do not know how so the PR is currently pending. It would be great if you can make it work.

**Comment by gsemet** [comment]
indeed, the pr got kicked :(

**Comment by BoPeng** [comment]
Update: I just tried again to fix my [f-string CodeMirror PR]((https://github.com/codemirror/CodeMirror/pull/5338)) because I use f-string a lot and would really like to see it used in JupyterLab. I guess in the open source world you have to get your hands dirty if you really want something.

**Comment by jasongrout** [comment]
Thanks for working on the f-string PR. Unfortunately, I don't have bandwidth to help with that, other than to cheer you on!

**Comment by BoPeng** [comment]
I totally understand. It was a bit frustrating because I expected @marijnh to help fix the last missing piece, at least explain the problem in more detail, but he just let the PR sit there, and might close it after a while. It is obvious that everyone has their own bandwidth problems.

**Comment by BoPeng** [comment]
Just to update that after my another attempt to fix the problem, @marijnh jumped in, fixed and merged the PR. The f-string formatting is now available in version 5.37.0 of codemirror that is released today. Now I see a good reason to update the codemirror version of JupyterLab.

**Comment by ian-r-rose** [comment]
That's great, @BoPeng.

**Comment by BoPeng** [comment]
@ian-r-rose, is it OK for you to update 5.35 to 5.37 in [codemirror/package.json](https://github.com/jupyterlab/jupyterlab/blob/6ef1d2a1cffada837a666c8b8efb1304b48c6d04/packages/codemirror/package.json#L41)? Nothing urgent but it would give me another reason to use JLab more. :smile:

**Comment by ian-r-rose** [comment]
Happy to merge a PR with it :)

**Comment by BoPeng** [comment]
Done. #4432

**Comment by jzf2101** [comment]
Is this ready to close?

**Comment by gsemet** [comment]
The recent update of codemirror added syntax coloration for f-string in Python. But makefile are still not supported by codemirror, and [they do not seem to be interested in it](https://github.com/codemirror/CodeMirror/issues/5408) :(

**Comment by gsemet** [comment]
thanks for your response. I do not use Makefile for jupyter itself, just i use it as helper in my python programs, and jupyterhub as a on-demand linux environment for training and so far it is extremely suited for this use case. Just editing Makefile is hard because of the damned tab thing (should be handled by #4135)

**Comment by fperez** [comment]
It seems the author of CM is uninterested in Makefile support, but for certain uses in software development Makefiles are still very important, and it's a real nuisance to not have it work out of the box... I found that there's finally a [working third-party Makefile mode for CM](https://github.com/V-Lor/codemirror-mode-makefile). I tested it by itself (without JupyterLab) and it seems to work perfectly fine, so I think it's worth revisiting this issue.

Adding that mode to our default package list and loading it in so Makefiles work out of the box would be awesome. I can't do more right now but will be needing this during the semester for teaching (it's been a thorn on my side for years), so if nobody else can work on it I'll try to make the fix later on. But I'd appreciate the help if anyone can beat me to it :)

**Comment by fperez** [comment]
I found [in the CoCalc code what seems to be another makefile mode](https://cocalc.com/share/public_paths/6e0bc050669357fdfcffe1b01eae650495965681/smc-webapp%2Fcodemirror%2Fmode%2Fmakefile.js).  I'm not sure if it's any better than the one linked in the previous comment - they look similar but are different enough that they'd need a bit of testing to be sure. However, both seem to follow fairly old APIs for integration into CM, instead of what I gather is the more modern way of exposing an entry point for loading a language mode.

Unfortunately my knowledge of the JLab codebase isn't enough to integrate this, given these don't seem to follow the more cleanly structured APIs that all other [language modes use](https://github.com/search?q=repo%3Ajupyterlab%2Fjupyterlab+codemirror%2Flang-python&type=code).  I couldn't just copy/change from the existing examples for other languages.

Leaving the above references for someone who later might have the cycles to look into this, so they find at least what seems to be the most recently updated options out there for Make support.

cc @ryanlovett for reference - not sure if you want to take a stab at this :)

**Comment by fperez** [comment]
After posting on gitter, @bollwyvl mentioned this:

> as it would be an extension anyway, the high road might be to get it wrapped for for jupyter-lsp with e.g. https://github.com/alexclewontin/make-lsp-vscode/tree/master/server

I don't have the cycles for that right now, but leaving it here for future reference, in hopes someone is interested/willing.
