### ISSUE TITLE
Upgrade upath in yarn.lock

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4513]
We've been seeing errors building JLab with node 10:

* https://github.com/bloomberg/bqplot/pull/644
* jupyter-widgets/ipywidgets#2061

https://github.com/yarnpkg/yarn/issues/5727 indicates this may have to do with upath, and upgrading upath would fix this.

**Comment by jasongrout** [comment]
Actually, maybe it is https://github.com/yarnpkg/yarn/issues/5761

**Comment by jasongrout** [comment]
See also https://github.com/jupyter-widgets/ipywidgets/issues/2061

**Comment by sahalsaad** [comment]
See this https://github.com/yarnpkg/yarn/issues/5727#issuecomment-386108534

**Comment by jasongrout** [comment]
This is fixed with the yarn upgrade in #4632.

**Comment by jasongrout** [comment]
Backported in #4666.

**Comment by j605** [comment]
This still happens when running `yarn run build:core`
```sh
$ cd jupyterlab/staging && jlpm && jlpm run build
(node:2206) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] Resolving packages...
[2/4] Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/home/jagan/srces/jupyterlab-git/src/jupyterlab/jupyterlab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
```

Also, I am using yarn 1.7.0
