### ISSUE TITLE
Stylesheet failed to load: /lab/api/themes/@jupyterlab/theme-light-extension/index.css

### ISSUE THREAD

**Issue by maartenbreddels** [jupyterlab/jupyterlab#4662]
Upgrading from 0.31.5 to 0.32.1 from conda-forge gives me a broken jupyter lab. Screenshot attached may help (it thinks I'm running from source?)
<img width="2079" alt="screen shot 2018-05-30 at 08 57 00" src="https://user-images.githubusercontent.com/1765949/40704156-aba47794-63e7-11e8-9ec5-401d90cbde06.png">

**Comment by maartenbreddels** [comment]
Installing using pip seems to work, odd, since I have a different conda environment where this conda package does work.

**Comment by saulshanabrook** [comment]
Can you try SHIFT reloading? i.e. reloading without cache. I think someone before had a problem where it was picking up the cached stylesheet which references non existent files now.

**Comment by rsandler00** [comment]
For me, running ` jupyter-lab --generate-config` fixed the problem. No idea why...

**Comment by blink1073** [comment]
I think this was a problem with our release process: that particular release didn't include the built themes.

**Comment by carluri** [comment]
> I think this was a problem with our release process: that particular release didn't include the built themes.

I'm having the same problem upgrading from 0.33.12  to 0.34.9.  Do you think this release has the same issue?

**Comment by blink1073** [comment]
Hmm, the themes files are in both the released wheel and tarball, so this is something else.  @carluri, are you seeing any errors in the Web Console?

**Comment by carluri** [comment]
> Hmm, the themes files are in both the released wheel and tarball, so this is something else. @carluri, are you seeing any errors in the Web Console?

I have jupyterlab with conda.  I found the themes under `/opt/conda/share/jupyter/lab/themes/@jupyterlab`

Looking closer at the error I'm getting after the upgrade, for the user `thisuser` the stylesheet that fails to load is
`/user/thisuser/user/thisuser/lab/api/themes@jupyterlab/theme-light-extension/index.css`

This path seems to be different than the one in the screeshot at the beginning of this thread. 

I downgraded to jupyterlab 0.33.12 and is working fine again though.

Let me know if there's anything else I can look to help.

thanks @blink1073

**Comment by saulshanabrook** [comment]
@carluri My browser loads this URL for the theme: `http://localhost:8888/lab/api/themes/@jupyterlab/theme-light-extension/index.css`

And I see `./themes/@jupyterlab/theme-light-extension/index.css` exists in my Jupyter Lab application directory:

```bash
$ jupyter lab path
Application directory:   /usr/local/share/jupyter/lab
User Settings directory: /Users/saul/Google Drive/Computer/Mackup/.jupyter/lab/user-settings
Workspaces directory: /Users/saul/Google Drive/Computer/Mackup/.jupyter/lab/workspaces
$ ls /usr/local/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/
674f50d287a8c48dc19ba404d20fe713.eot   b06871f281fee6b241d60582ae9369b9.ttf   fee66e712a8a08eef5805a46892932ad.woff  package.json
af7ae505a9eed503f8b8e6982036873e.woff2 embed.css                              index.css
```

Maybe it would be helpful to look  at what is in your jupyter lab application directory to see if there is the `index.css` in the proper subdirectory?

**Comment by carluri** [comment]
@saulshanabrook  yes I did check the files and the index.css exists under the themes directory in the Application directory.  It seems as if when I upgrade to 0.34 is looking for that file somewhere else.

**Comment by saulshanabrook** [comment]
I am on 0.34.3 and it seems to be finding it there. Hm... Your URL tha tyou posted in rather long? Do you know why there are two `/user/thisuser` in it? Also why there is no slash after `themes`?

**Comment by carluri** [comment]
@saulshanabrook I don't know why the URL gets "duplicated".  The following is the output from the console.  (the missing slash after themes was my typo)

`host/user/thisuser/user/thisuser/lab/api/themes/@jupyterlab/theme-light-extension/index.css net::ERR_ABORTED 404 (Not Found)`

the index.css is indeed located under the Application directory.

**Comment by blink1073** [comment]
@carluri, what is the output of "jupyter lab paths"?

**Comment by carluri** [comment]
@blink1073 

```
Application directory:   /opt/conda/share/jupyter/lab
User Settings directory: /home/thisuser/.jupyter/lab/user-settings
Workspaces directory /home/thisuser/.jupyter/lab/workspaces
```

**Comment by blink1073** [comment]
Okay, so the problem is in the creation of the `themes_url`.   That logic was recently fixed in https://github.com/jupyterlab/jupyterlab_server/pull/59, and will be available in the next release.

**Comment by blink1073** [comment]
I'm going to close this, but please comment back if you still see the behavior in the 1.0 release.

**Comment by 00krishna** [comment]
I am still seeing this. I have Jupyter labl version 0.34.9 installed and getting the same errors.

**Comment by mouradmourafiq** [comment]
I am having a similar issue, only works with `0.33.12`. Any update on this?

**Comment by mouradmourafiq** [comment]
I just tried the `jupyterlab==v1.0.0a1` and I can still see the problem.

**Comment by ku2482** [comment]
I had a same issue using jupyterlab==0.35.4 and google chrome.

When I tried to open with safari, the problem didn't occur.
Then I deleted all cache of chrome and tried once more, which works.

I don't know the exact reason, but deleting cache of the browser may help you.

**Comment by YuryBolkonsky** [comment]
Same issue now  jupyterlab==0.35.4 and google chrome

**Comment by krvkir** [comment]
Same issue with jupyterlab=1.0.4 both in chrome and firefox. Clearing cache didn't help.

Rebuilding with `jupyter lab build` fixed this issue for me.

In case it helps, here are jupyter logs before rebuilding:
```
[W 13:19:49.496 LabApp] 500 GET /lab/api/settings/?1564654789478 (::1): Failed validating schema (@jupyterlab/apputils-extension:package): '^1.5.0' is not valid under any of the given schemas
    
    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}
    
    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[W 13:19:49.496 LabApp] Failed validating schema (@jupyterlab/apputils-extension:package): '^1.5.0' is not valid under any of the given schemas
    
    Failed validating 'anyOf' in metaschema['properties']['dependencies']['additionalProperties']:
        {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/stringArray'}]}
    
    On schema['dependencies']['@phosphor/commands']:
        '^1.5.0'
[E 13:19:49.497 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab/workspaces/auto-K",
      "X-Xsrftoken": "2|50743ec5|66e75d66a7830a5f2e61ca45b2b96e52|1563528499",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1564505143|23:username-localhost-8888|44:MWVmYzRlZjVkM2M2NGUwOWJjZjc1NWVhMTVhNzMzYzk=|6fa746abe2cc45f5a67397016902a0fa8ab7b810d47a11acaaf269ef48f00abb\"; CSRF-Token-JCHCE=XRFneej6e3gdbwJLAAM5muvPzrFvjX7y; _xsrf=2|50743ec5|66e75d66a7830a5f2e61ca45b2b96e52|1563528499; username-localhost-8889=\"2|1:0|10:1564654587|23:username-localhost-8889|44:NWY1YjNmMTc1ZGFlNGY5YWExMmI1NmEzM2VhYTkwNmI=|244d379213e0541ce2cd682d79aa55ea7fc32cae60c422ca845b51e4c8301141\"",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 13:19:49.497 LabApp] 500 GET /lab/api/settings/?1564654789478 (::1) 4.93ms referer=http://localhost:8888/lab/workspaces/auto-K
[W 13:19:50.070 LabApp] The extension "jupyterlab_bokeh" is outdated.
    
[I 13:19:50.070 LabApp] Build is up to date

```

**Comment by blink1073** [comment]
@ MatMaul offered this advice in #7815:

> it is probably related to a bug in Chrome with self signed certs ?

> More infos here:
https://stackoverflow.com/questions/58086327/google-chrome-neterr-too-many-retries
https://bugs.chromium.org/p/chromium/issues/detail?id=488043
