### ISSUE TITLE
Suggestions on extension manager extension.

### ISSUE THREAD

**Issue by BoPeng** [jupyterlab/jupyterlab#5053]
JLab lacks a UI to explore and install third-party extensions, similar to RStudio's install  packages, Atoms' extension manager etc. It took me, a relatively experienced JLab user some trouble to find [nbdime JLab extension](https://github.com/jupyter/nbdime) and I believe most new users would just assume that there is no such feature for JLab (and turn away). Jupyter has [jupyter_contrib_extension](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) although it supports only selected extensions.

I found [jupyterlab-discovery](https://github.com/vidartf/jupyterlab_discovery). I cannot make it work right now because my environment is messed up but I believe this is something that deserves to be a core component of JLab. What do you think?

**Comment by BoPeng** [comment]
https://github.com/jupyterlab/jupyterlab/tree/master/packages/extensionmanager-extension
The discovery extension is in JupyterLab now. You'll need to open your advanced settings editor to enable it because until some things settle down, it is disabled by default.

**Comment by afshin** [comment]
@BoPeng:

https://github.com/jupyterlab/jupyterlab/tree/master/packages/extensionmanager-extension

The discovery extension is in JupyterLab now. You'll need to open your advanced settings editor to enable it because until some things settle down, it is disabled by default:

<img width="1066" alt="extension manager" src="https://user-images.githubusercontent.com/159529/43687965-814d98b6-98d7-11e8-9cc0-94f60211350b.png">

**Comment by BoPeng** [comment]
Thanks, I enabled the extension, but I only see the installed (enabled or not) packages. I can search for new packages (e.g. `google drive`, `vim`) but I cannot find a way to browse all extensions. Is there any way to do it?

**Comment by afshin** [comment]
You must enter some search item. It can be simply a space, but the way the extension manager works is by searching. I believe it is modeled on the way Visual Studio Code does it.

If you have UI feedback or suggestions or issues, feel free to post them, please.

cc: @vidartf

**Comment by BoPeng** [comment]
Thanks! Here are my observations/comments so far:

1. The "search space" trick lists all the packages, but I would change the hint text from `SEARCH`
to something like `SEARCH (enter space to list all)` to make this operation clearer.

2. I installed nbdime-jupyterlab but not sure how to use it (no visible change to JLab is found). It would be helpful to provide a link next to package names to corresponding github, read-the-doc, or at least npm pages.

3. Is it possible to change the `enable: false` default value to `enable: auto` so that the extension will be made available if `node` command is detected when JLab is started?

**Comment by t-makaro** [comment]
My observations are:
1. My big issue is that when I install an extension, and jupyter needs to be rebuilt, that there is no indication of build progress. There is a loading bar, but it is 5% done, 90%? Is it making progress at all? Rebuilding takes a while, and that needs to be better conveyed to the user.

2. In regards to the, "not sure how to use" an extension once it's installed. When you search for extensions in VS code, you can click on any extension in the list and get a sort of store front listing. That would be really nice. Even if it links to a completely different website per extension.

3. When an extension requires a server-side component, and it asks "would you like to continue?" in a pop-up, the options "ok", and "cancel" are not totally clear. "Cancel" is, but "ok" would be better replaced with "yes". 

4. It would be really nice, if when an extension needed a server-side component, that it would give me an indication of how to get it.

**Comment by vidartf** [comment]
@BoPeng Do you consider this issue fixed with #5055 merged?

----------------------

@t-makaro :

> Rebuilding takes a while, and that needs to be better conveyed to the user.

I agree, but it can be really tricky to obtain this information. Do you have any suggestions for how best to achieve this?

2. should be fixed in #5055.

3. should be a simple fix (either change the labels, or change the prompt question). Do you want to do a PR for this?

> It would be really nice, if when an extension needed a server-side component, that it would give me an indication of how to get it.

The original code contained something like this (and even could help you run those commands), but this code is not tested thoroughly, so it was left out of the initial PR. I'll submit a PR containing that functionality once my calendar clears up more.

**Comment by BoPeng** [comment]
> @BoPeng Do you consider this issue fixed with #5055 merged?

My concern on extensionmanager being hidden deeply inside advanced settings is not resolved. With work towards show/hide side panels (https://github.com/jupyterlab/jupyterlab/issues/5054), I believe the extension manger should be enabled but hidden by default. That is to say, 

1. Setting on enable extension manager should be `on` by default (or `hidden` if allowed)
2. Admins can disable extension manager for installations that disallow user installation of extensions.
3. Users can show extension manager by simply selecting `Window -> Extension Manager`.

My point is that JLab is built on extensions and extension manager is too important to be buried this deep. While very few new users (including somewhat experienced users like me) would explore advanced settings and knows how to enable extension manager, a lot of them would check `Window -> ` and see what are available.

**Comment by vidartf** [comment]
> My point is that JLab is built on extensions and extension manager is too important to be buried this deep.

I think this was meant as a temporary solution until it was vetted and made more robust. By including it like this, we can work on it and experiment with it, but still remove it if any fundamental problems appear. There is also the issue that it should be disabled if a compatible version Node is not available on the server.

**Comment by BoPeng** [comment]
>  it should be disabled if a compatible version of Node is not available on the server.

I disagree. The discovery part is more important than installation because users can always try to get node installed or fixed if they found something interesting extensions.

**Comment by vidartf** [comment]
> The discovery part is more important than installation because users can always try to get node installed or fixed if they found something interesting extensions.

Then maybe what we should do is to have the server extension indicate a lack of build capabilities, and have the extension manager display informational text to that regard. E.g. "The extension manager requires Node.js to be installed on the server." Does this seem like a decent solution?

**Comment by blink1073** [comment]
Yep, along with "Please contact your system administrator"

**Comment by vidartf** [comment]
@BoPeng Hah, on re-reading the entire issue, I see that this was among your earlier suggestions, so I guess we are agreed on that point.

I'll try to do a PR that fixes this and #5042!

**Comment by krassowski** [comment]
Any news on that in 2019? Every now and then I land on this page after some googling just to remind myself that I need to enable the extension manager before I can install extensions using this wonderful sidebar feature.

Also, it's pretty counter intuitive that the `Search results` are collapsed by default. I mean this:
![peek 2019-01-04 14-10](https://user-images.githubusercontent.com/5832902/50692097-aab26680-102a-11e9-917e-097cea6ba279.gif)

**Comment by BoPeng** [comment]
@vidartf Any update? Has there been any discussion/conclusion if the extension manager should be enabled by default?

**Comment by dkipping** [comment]
> > @BoPeng Do you consider this issue fixed with #5055 merged?
> 
> My concern on extensionmanager being hidden deeply inside advanced settings is not resolved. With work towards show/hide side panels (#5054), I believe the extension manger should be enabled but hidden by default. That is to say,
> 
> 1. Setting on enable extension manager should be `on` by default (or `hidden` if allowed)
> 2. Admins can disable extension manager for installations that disallow user installation of extensions.
> 3. Users can show extension manager by simply selecting `Window -> Extension Manager`.
> 
> My point is that JLab is built on extensions and extension manager is too important to be buried this deep. While very few new users (including somewhat experienced users like me) would explore advanced settings and knows how to enable extension manager, a lot of them would check `Window -> ` and see what are available.

Is there even a possibility for admins to completely disable the extension manager? I mean also preventing user from enabling it in the advanced settings?

**Comment by jasongrout** [comment]
> Is there even a possibility for admins to completely disable the extension manager? I mean also preventing user from enabling it in the advanced settings?

Clarifying point: The extension manager extension can be enabled/disabled like any other extension. If the extension manager extension is enabled, it adds a setting section to the Advanced Settings for showing the extension manager panel in the sidebar. If that Advanced Setting is enabled, then the extension manager panel shows in the sidebar.

I think an admin can disable the extension manager plugin, just like any other extension (IIRC there is a system-wide config file that allows an admin to disable plugins). This is separate from a user enabling the UX through Advanced Settings.

Also, IIRC an admin can override the setting default for the UX enablement to enable the extension manager UX by default on a particular site, possibly addressing @BoPeng's concern more completely.

**Comment by vidartf** [comment]
> Any update? Has there been any discussion/conclusion if the extension manager should be enabled by default?

There hasn't really been any discussion, but it should definitely be considered for 1.0. I'm not sure who to ping here for that discussion. Maybe @jasongrout and @ellisonbg ? You seemed to have opinions about this when it was first merged :)

**Comment by sho-87** [comment]
is there a way for the extension manager to indicate when a new version of the installed extension is available, and then provide a way to do the update? right now I dont think its possible to tell that an update available, and even if there is it seems the only way to update it is to first uninstall and then reinstall the extension...

**Comment by vidartf** [comment]
@sho-87 This should definitely be possible, and should already be implemented (at least in pre-release of 1.0). If there is an update (that is compatible with the current version of lab) there should be a button for the entry "Update". If this is not the case for you, could you please open a new bug-report ?

**Comment by jqluisneumann** [comment]
Is it possible for the list of installed extensions to be cached? On my workplace, I need to go to the guest network to update any packages/extensions/conda/etc as they are all blacklisted. However, I open JupyterLab pointing to a network drive where all my work is stored, and hence need to be in our network.

As such, if i start Jupyter lab under my network, the extension manager never gets populated, and in the anaconda prompt I see errors such as ```Failed to fetch package metadata for '@jupyter-widgets/jupyterlab-manager```

As soon as I switch networks the list gets populated. I can understand that installation/search might need internet access, and that Lab tried to update the metadata so I check/upgrade extensions, but the extension manager should populate the list of installed extensions without any need to fetch metadata so one can disable/uninstall extensions without network access.

**Comment by krassowski** [comment]
Two suggestions:
- the version of an installed extension should be displayed in the manager (especially because of #)
- the search should perform partial matching against the extension title (currently it's very difficult to find many extensions which follow snake_case naming schema and do not repeat the keywords in the description).

Should we keep adding suggestions here or open new issues?

**Comment by vidartf** [comment]
> Should we keep adding suggestions here or open new issues?

Please open new issues. This issue is already a bit of a mess that I would argue for splitting any remaining tasks out into new issues as well.

**Comment by saulshanabrook** [comment]
I am closing this, now that the extension manager is enabled by default. It still seems like there are many good ideas in here! Please open issues (or even better, PRs!) for those separately so we can better track them.
