### ISSUE TITLE
No keyboard way to get input focus in the console

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#644]
If the input area doesn't have focus, there seems to be no keyboard-based way to get it currently.

This happens on console first start (thus requiring a click to start typing) and if for example an `input()` call is made, which will move focus to the stdin area. After entering text, the new input area won't be focused and there's no way to re-focus it with the keyboard.

Suggested fixes:
- after stdin usage and on start, input area should have focus by default, thus not requiring further user action.
- `Enter` should focus it, allowing users to regain focus in other situations that may arise. This is how the notebook works, so it's the most natural thing for users to try.

**Comment by sccolbert** [comment]
Replacing "bug" with "enhancement".

**Comment by fperez** [comment]
no prob, it was borderline, but agreed :)

**Comment by jasongrout** [comment]
On start, the console now focuses the input. After stdin usage and after pressing enter, the cursor is still not focused on the input cell.

**Comment by jasongrout** [comment]
Interestingly, now if you just do *one* `input()`, the input is not focused, but if you do *two* `input(), input()`, the input box *is* focused.

**Comment by ClaytonPassmore** [comment]
@jasongrout I was with you when that weird "one doesn't work but two does" behavior happened but I can't reproduce. Everything is working fine for me on master. Focus goes to the input box(es) as expected. Obviously focus still does not return to the console, though.

**Comment by ClaytonPassmore** [comment]
@blink1073 This is fixed, right? Can we close this issue?

**Comment by blink1073** [comment]
Not quite.  It is better, but we still have some work to do to make this seamless.
