### ISSUE TITLE
Cannot read property 'addFactory' of undefined

### ISSUE THREAD

**Issue by david-waterworth** [jupyterlab/jupyterlab#6670]
I installed the pre release version of JupyterLab () in order to use [altair](**url**). 

> Installing collected packages: jupyterlab-server, jupyterlab
>   Found existing installation: jupyterlab-server 0.2.0
>     Uninstalling jupyterlab-server-0.2.0:
>       Successfully uninstalled jupyterlab-server-0.2.0
>   Found existing installation: jupyterlab 0.35.6
>     Uninstalling jupyterlab-0.35.6:
>       Successfully uninstalled jupyterlab-0.35.6
> Successfully installed jupyterlab-1.0.0a9 jupyterlab-server-1.0.0rc0

It initially worked but I noticed ipywidgets would no longer display after the update, so I upgraded node and npm, and now it's totally broken, I cannot start a kernel, it reports `Cannot read property 'addFactory' of undefined`.

Rolling back to 0.35.6 fixes the problem.

node -v
v10.16.0

npm -v
6.9.0

Am I running supported / recomended verisons of node and npm? I'm using ubuntu 18.04

EDIT:

It appears the issue is with either the ipwidget extension, or the extension manager itself.

If I remove all extensions, everything works fine (except of course the widgets don't display).

If I try reinstalling `@jupyter-widgets/jupyterlab-manager` from the ui I get 

> Error communicating with server extension. Consult the documentation for how to ensure that it is enabled.
> Reason given:
> Error: 500 (Internal Server Error)

```
model.js:572 Uncaught (in promise) Error: 500 (Internal Server Error)
    at Object.handleError (model.js:572)
    at model.js:455
```

If I install from the console:

`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

> An error occured.
> TypeError: _extract_package() got an unexpected keyword argument 'quiet'
> See the log file for details:  /tmp/jupyterlab-debug-ece7ailo.log

`cat /tmp/jupyterlab-debug-ece7ailo.log`

cat /tmp/jupyterlab-debug-ece7ailo.log

> Node v10.16.0
> 
> > /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager
> npm notice 
> npm notice 📦  @jupyter-widgets/jupyterlab-manager@0.41.0
> npm notice === Tarball Contents === 
> npm notice 2.3kB  package.json        
> npm notice 1.5kB  LICENSE             
> npm notice 2.0kB  README.md           
> npm notice 277B   lib/index.d.ts      
> npm notice 1.0kB  lib/index.js        
> npm notice 5.3kB  lib/manager.d.ts    
> npm notice 14.1kB lib/manager.js      
> npm notice 1.9kB  lib/output.d.ts     
> npm notice 5.9kB  lib/output.js       
> npm notice 830B   lib/plugin.d.ts     
> npm notice 7.3kB  lib/plugin.js       
> npm notice 956B   lib/renderer.d.ts   
> npm notice 4.3kB  lib/renderer.js     
> npm notice 216B   lib/semvercache.d.ts
> npm notice 972B   lib/semvercache.js  
> npm notice 375B   schema/plugin.json  
> npm notice === Tarball Details === 
> npm notice name:          @jupyter-widgets/jupyterlab-manager          
> npm notice version:       0.41.0                                       
> npm notice filename:      jupyter-widgets-jupyterlab-manager-0.41.0.tgz
> npm notice package size:  12.4 kB                                      
> npm notice unpacked size: 49.3 kB                                      
> npm notice shasum:        af8649d083c3a8ee415e8f3941421f0c29c57974     
> npm notice integrity:     sha512-SYDHLMGtalTcF[...]q7a/76+qDNRGQ==     
> npm notice total files:   16                                           
> npm notice 
> jupyter-widgets-jupyterlab-manager-0.41.0.tgz
> 
> Fetching URL: https://registry.npmjs.org/@jupyter-widgets%2Fjupyterlab-manager
> Traceback (most recent call last):
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
>     yield
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 82, in start
>     ans = self.run_task()
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in run_task
>     for arg in self.extra_args
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
>     for arg in self.extra_args
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/commands.py", line 316, in install_extension
>     return handler.install_extension(extension)
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/commands.py", line 517, in install_extension
>     info = self._install_extension(extension, tempdir)
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/commands.py", line 1396, in _install_extension
>     version = self._latest_compatible_package_version(name)
> 
>   File "/home/david/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/jupyterlab/commands.py", line 1485, in _latest_compatible_package_version
>     '%s@%s' % (name, version), tempdir, quiet=True)
> 
> TypeError: _extract_package() got an unexpected keyword argument 'quiet'
> 
> Exiting application: jupyter
>

**Comment by jasongrout** [comment]
Pre releases are being released a lot lately, and the ipywidgets extension hasn't been updated yet. I would suggest waiting a few days, and we'll update ipywidgets to the RC.

**Comment by vidartf** [comment]
Fixed by #6663.

**Comment by david-waterworth** [comment]
I installed the specific commit you referenced

pip install git+git://github.com/jupyterlab/jupyterlab.git@558893aa972b4bc61c6e6a8066fb699bbf67a3ee

It doesn't fix this issue, what it does fix is I can now install the ipywidget addon, before I was seeing `TypeError: _extract_package() got an unexpected keyword argument 'quiet'`

But I still see `Cannot read property 'addFactory' of undefined` when I try and start a kernel after adding ipywidget and rebuilding (before I simply couldn't add or rebuild, originally when I upgraded I had the addin enabled)

**Comment by vidartf** [comment]
I think that is because ipywidgets has not yet been updated to support the lab RC (if you run `jupyter labextension update @jupyter-widgets/jupyterlab-manager`, you should hopefully get an error message to that effect).

**Comment by david-waterworth** [comment]
@vidartf that sounds likely - there is no error though, it happily installs and then jupyter lab is unusable (for me at least). I assume that there's no need to log an issue with ipywidgets?
