### ISSUE TITLE
jupyterlab wont launch - blank screen since 1.0

### ISSUE THREAD

**Issue by tjbergst** [jupyterlab/jupyterlab#6858]
Technical Specs:
Windows 10 Enterprise
Python 3.6.7
Jupyter Notebook 6.0.0
Jupyterlab 1.0.2
Firefox 60.7.2, Chrome 75.0.3770.142

I am excited to start using the new 1.0 but I cannot get lab to launch. I am having an issue similar to #6119 where jupyterlab only shows a blank screen on launch since updating to 1.0. The classic notebook launches fine.

Errors in the terminal: 
```
[E 17:19:30.631 LabApp] Could not open static file ''
[W 17:19:30.676 LabApp] 404 GET /main.ede7b15ba64ec4b33ae5.js (::1) 245.99ms referer=http://localhost:8888/lab?token=3304280eb4feaf4d28818dd42075ff5c97617e16d044578e
[W 17:19:30.679 LabApp] 404 GET /vendors~main.5f0ef20c1b446f440307.js (::1) 2.00ms referer=http://localhost:8888/lab?token=3304280eb4feaf4d28818dd42075ff5c97617e16d044578e
```

In the chrome console:
```
(http://localhost:8888/main.ede7b15ba64ec4b33ae5.js) Failed to load resource: the server responded with a status of 404 (Not Found)
(http://localhost:8888/vendors~main.5f0ef20c1b446f440307.js) Failed to load resource: the server responded with a status of 404 (Not Found)
```
Both of these files do exist in my ~\share\jupyter\lab\static directory.

Things I've tried with no change:
- clearing browser cache
- specifying port other than 8888
- specifying --core-mode
- downgrading notebook to 5.7.X
- downgrading tornado to 5.1.X
- fresh conda environment with various versions of python 
- completely uninstalling python (including anaconda-clean, removing .jupyter, .ipython) and installing again fresh

Any thoughts or other things to try?

**Comment by jasongrout** [comment]
Run with the `--debug` flag, which will print out exactly which file on disk it is looking for and not finding.

**Comment by tjbergst** [comment]
Output:
```
[D 20:02:19.464 LabApp] Searching ['C:\\Users\\trevor\\Documents\\Work', 'C:\\Users\\trevor\\.jupyter', 'C:\\Users\\trevor\\AppData\\Local\\Continuum\\miniconda3\\envs\\py36-prime\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 20:02:19.466 LabApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 20:02:19.466 LabApp] Looking for jupyter_config in C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\etc\jupyter
[D 20:02:19.467 LabApp] Looking for jupyter_config in C:\Users\trevor\.jupyter
[D 20:02:19.468 LabApp] Looking for jupyter_config in C:\Users\trevor\Documents\Work
[D 20:02:19.469 LabApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 20:02:19.469 LabApp] Looking for jupyter_notebook_config in C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\etc\jupyter
[D 20:02:19.478 LabApp] Loaded config file: C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\etc\jupyter\jupyter_notebook_config.json
[D 20:02:19.479 LabApp] Looking for jupyter_notebook_config in C:\Users\trevor\.jupyter
[D 20:02:19.481 LabApp] Loaded config file: C:\Users\trevor\.jupyter\jupyter_notebook_config.py
[D 20:02:19.481 LabApp] Looking for jupyter_notebook_config in C:\Users\trevor\Documents\Work
[D 20:02:19.506 LabApp] [nb_conda_kernels] refreshing conda info
[E 20:02:21.448 LabApp] [nb_conda_kernels] couldn't call conda:
    Command '['C:\\Users\\trevor\\AppData\\Local\\Continuum\\miniconda3\\Scripts\\conda.exe', 'info', '--json']' returned non-zero exit status 1.
[I 20:02:21.449 LabApp] [nb_conda_kernels] enabled, 0 kernels found
[D 20:02:21.456 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 20:02:21.458 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\etc\jupyter\jupyter_notebook_config.json
[D 20:02:21.469 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\trevor\.jupyter\jupyter_notebook_config.json
[I 20:02:23.815 LabApp] JupyterLab extension loaded from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\jupyterlab
[I 20:02:23.817 LabApp] JupyterLab application directory is C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\share\jupyter\lab
[I 20:02:23.821 LabApp] Serving notebooks from local directory: C:\Users\trevor\Documents\Work
[I 20:02:23.822 LabApp] The Jupyter Notebook is running at:
[I 20:02:23.823 LabApp] http://localhost:8888/?token=d332632cf23f8b78d47bdcf400b5c7e2a0739745c8f3830a
[I 20:02:23.823 LabApp]  or http://127.0.0.1:8888/?token=d332632cf23f8b78d47bdcf400b5c7e2a0739745c8f3830a
[I 20:02:23.824 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:02:23.858 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/trevor/AppData/Roaming/jupyter/runtime/nbserver-17044-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=d332632cf23f8b78d47bdcf400b5c7e2a0739745c8f3830a
     or http://127.0.0.1:8888/?token=d332632cf23f8b78d47bdcf400b5c7e2a0739745c8f3830a
[D 20:02:38.638 LabApp] Accepting token-authenticated connection from ::1
[D 20:02:38.642 LabApp] Using contents: services/contents
[D 20:02:38.650 LabApp] 200 GET /lab?token=d332632cf23f8b78d47bdcf400b5c7e2a0739745c8f3830a (::1) 13.00ms
[D 20:02:38.683 LabApp] Using contents: services/contents
[D 20:02:38.749 LabApp] Path base/images/favicon.ico served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\base\images\favicon.ico
[D 20:02:38.764 LabApp] Path components/jquery-ui/themes/smoothness/jquery-ui.min.css served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\components\jquery-ui\themes\smoothness\jquery-ui.min.css
[D 20:02:38.769 LabApp] Path components/jquery-typeahead/dist/jquery.typeahead.min.css served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\components\jquery-typeahead\dist\jquery.typeahead.min.css
[D 20:02:38.787 LabApp] Path style/style.min.css served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\style\style.min.css
[D 20:02:38.792 LabApp] Path components/es6-promise/promise.min.js served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\components\es6-promise\promise.min.js
[D 20:02:38.814 LabApp] Path components/react/react.production.min.js served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\components\react\react.production.min.js
[E 20:02:38.817 LabApp] Could not open static file ''
[D 20:02:38.818 LabApp] Path components/create-react-class/index.js served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\components\create-react-class\index.js
[D 20:02:38.822 LabApp] Path components/requirejs/require.js served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\components\requirejs\require.js
[D 20:02:38.826 LabApp] Path base/images/logo.png served from C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\lib\site-packages\notebook\static\base\images\logo.png
[W 20:02:38.829 LabApp] 404 GET /main.ede7b15ba64ec4b33ae5.js (::1) 147.00ms referer=http://localhost:8888/lab?token=d332632cf23f8b78d47bdcf400b5c7e2a0739745c8f3830a
[D 20:02:38.832 LabApp] Using contents: services/contents
[W 20:02:38.834 LabApp] 404 GET /vendors~main.5f0ef20c1b446f440307.js (::1) 4.00ms referer=http://localhost:8888/lab?token=d332632cf23f8b78d47bdcf400b5c7e2a0739745c8f3830a
```

The GET just shows the top level /, but I'm not sure where it shows where that would be on disk?

**Comment by jasongrout** [comment]
It's the Path ... served from ... lines we are looking at. Are there any for the main javascript file that it can't find?

**Comment by jasongrout** [comment]
Sorry, I just looked at the code and it looks like 404 errors don't show those lines or even where it was trying to look for the path.

**Comment by blink1073** [comment]
Hi @tjbergst, if you type `jupyter lab path` it will show you where jupyterlab thinks it has put the application assets.  In the "Application Directory" you should see `static/main.ede7b15ba64ec4b33ae5.js`.

E.g. on my Windows 10 machine with JuypyterLab 1.0.2:

```
(lab-test) steve: /c/users/steve/miniconda/envs/lab-test/share/jupyter/lab/static
$ ls | grep main
main.ede7b15ba64ec4b33ae5.js
main.ede7b15ba64ec4b33ae5.js.map
vendors~main.5f0ef20c1b446f440307.js
vendors~main.5f0ef20c1b446f440307.js.map
```

**Comment by tjbergst** [comment]
@blink1073 `jupyter lab path` outputs: 
`C:\Users\trevor\AppData\Local\Continuum\miniconda3\envs\py36-prime\share\jupyter\lab`

Which does contain both noted *main*.js files.

**Comment by sursu** [comment]
Ubuntu 18.04.2
Just updated JupyterLab to 1.0.2.
I have the same problem:

![Peek 2019-07-22 14-09](https://user-images.githubusercontent.com/12001304/61631451-b09c2c00-ac8a-11e9-99db-6e87ca59e8e0.gif)

**Comment by komjum6** [comment]
Windows 10
Same here, also just updated.

```
[I 21:41:07.498 LabApp] JupyterLab extension loaded from d:\users\emperor justinian\anaconda\lib\site-packages\jupyterlab
[I 21:41:07.498 LabApp] JupyterLab application directory is d:\users\emperor justinian\anaconda\share\jupyter\lab
[I 21:41:07.514 LabApp] Serving notebooks from local directory: C://Users//Emperor Justinian/
[I 21:41:07.514 LabApp] 0 active kernels
[I 21:41:07.514 LabApp] The Jupyter Notebook is running at:
[I 21:41:07.514 LabApp] http://localhost:8888/?token=b8bb8cc462ee11f0fdad42636a878ce413243f12a6fc57a9
[I 21:41:07.514 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:41:07.514 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=b8bb8cc462ee11f0fdad42636a878ce413243f12a6fc57a9
[I 21:41:07.654 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 21:41:07.761 LabApp] 404 GET /static/lab/vendors~main.486ebe049d79c9947627.js (::1) 41.89ms referer=http://localhost:8888/lab?token=245f4adf757a601e39d4ab04391e67c874c962c8fcfe9507
[W 21:41:08.125 LabApp] 404 GET /static/lab/vendors~main.486ebe049d79c9947627.js (::1) 1.00ms referer=http://localhost:8888/lab
[I 21:43:46.612 LabApp] 302 GET / (::1) 1.02ms
[W 21:43:46.662 LabApp] 404 GET /static/lab/vendors~main.486ebe049d79c9947627.js (::1) 2.99ms referer=http://localhost:8888/lab?
[W 21:43:46.987 LabApp] 404 GET /static/lab/vendors~main.486ebe049d79c9947627.js (::1) 1.00ms referer=http://localhost:8888/lab?
[I 21:44:00.177 LabApp] Kernel started: b4f08588-8bb7-47e1-9758-6d4e0069c47a
[I 21:44:01.353 LabApp] Adapting to protocol v5.1 for kernel b4f08588-8bb7-47e1-9758-6d4e0069c47a
[I 21:44:06.338 LabApp] 302 GET /notebooks/ (::1) 1.00ms
[I 21:44:06.393 LabApp] Starting buffering for b4f08588-8bb7-47e1-9758-6d4e0069c47a:5eaca87998c04795840a75b4036fda6f
[W 21:44:12.713 LabApp] 404 GET /static/lab/vendors~main.486ebe049d79c9947627.js (::1) 2.99ms referer=http://localhost:8888/lab
[W 21:44:12.868 LabApp] 404 GET /static/lab/vendors~main.486ebe049d79c9947627.js (::1) 1.99ms referer=http://localhost:8888/lab
```

**Comment by blink1073** [comment]
What does `pip list | grep jupyterlab` show (assuming you have Git Bash)?

**Comment by sursu** [comment]
![image](https://user-images.githubusercontent.com/12001304/61828724-a71beb00-ae67-11e9-9785-310b714aebb3.png)

**Comment by tjbergst** [comment]
```
 > conda list | findstr jupyterlab
jupyterlab                1.0.2                    py36_0    conda-forge
jupyterlab_server         1.0.0                      py_1    conda-forge
```

**Comment by tjbergst** [comment]
Wow, so good news, it's now working. When I did the `conda list` I also checked `pip list` afterwards which reported:
```
 > pip list | findstr jupyterlab
jupyterlab                         1.0.2
jupyterlab-server                  0.3.0
```

It seems there was a hidden old version of `jupyterlab-server` floating around. When I called `pip uninstall jupyterlab-server==0.3.0` it removed the old version from my roaming directory:
`C:\users\trevor\appdata\roaming\python\python36\site-packages`

Once removed, jupyterlab successfully launched. I'm not sure how they got into my roaming directory, I guess they could've been leftover from a previous install? I ran `anaconda-clean` and scrubbed through my `~/appdata/local` when I wiped anaconda and reinstalled.

**Comment by sursu** [comment]
It appears that `pip install -U jupyterlab` is broken. This is how I have upgraded the JupyterLab.

I have uninstalled it: `pip uninstall jupyterlab` and then installed it again: `pip uninstall jupyterlab`.

Now it runs fine.

**Comment by jasongrout** [comment]
Sounds like @tjbergst's original issue is solved. Good that @sursu's issue is solved too.

**Comment by carluri** [comment]
I'm still having this problem and none of the above worked. 

The console output in chrome shows the following:

`static/lab/main.0e25181b5ee7a109080f.js net::ERR_ABORTED 404 (Not Found)`

I'm also running jupyterlab via the jupyterhub in case that helps.

**Comment by JustinMoser** [comment]
Hi,
I have the same issue running JupyterLab inside of JupyterHub.

I upgraded my JupyterLab version by `pip uninstall jupyterlab` and then `pip install jupyterlab`

and I now have a blank screen when going to `/lab`

the error message is:

```
/hub/main.5fb27a388329dc4c781d.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

/hub/vendors~main.053b2e57df6bcd10af93.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

I have tried uninstalling jupyterlab and jupyterlab-server however none of the above solutions work for me.
