### ISSUE TITLE
Endless loop when launching Jupyter Lab

### ISSUE THREAD

**Issue by fabioanza** [jupyterlab/jupyterlab#8187]
Hi, I currently use Jupyter Notebook for my research and I wanted to start learning Jupyter Lab. I have anaconda so I installed Jupyter lab with the following command line
"conda install -c conda-forge jupyterlab"
Then when I try to launch it with "jupyter lab" it enters an endless loop in which it closes the browser page it just opened and opens a new one with a slightly different address. An example of the address it is trying to open is "localhost:8889/lab/workspaces/auto-m?clone=auto-g"
and the part auto-m and auto-g simply iterate and change the letter after the dash. 

You can also check what I see in the terminal, which is always the same line 
[I 09:18:50.342 LabApp] 301 GET /lab/workspaces/auto-O/?clone=auto-A (::1) 0.59ms
with slightly different parameters as 0.59ms,0.74ms etc.

<img width="870" alt="Terminal" src="https://user-images.githubusercontent.com/46694437/78694152-1aa84000-78b1-11ea-9b67-2bf00da3555d.png">

I am not entirely sure why this happens and I could not find another instance of this issue

Thank you for your help!

**Comment by jasongrout** [comment]
Please provide the information requested in the issue template, including:

```
## Context

<!--Complete the following for context, and add any other relevant context-->

- Operating System and version:
- Browser and version:
- JupyterLab version:
```

**Comment by fabioanza** [comment]
Sorry, here it is:
- MacOS Catalina 10.15.4
- Safari 13.1
- Jupyterlab 1.1.4

**Comment by jasongrout** [comment]
Please upgrade JupyterLab. I think 1.2.8 should work, or 2.0.1 as well. This is a known issue with a bug in Safari that was fixed in JupyterLab.

**Comment by fabioanza** [comment]
I try to update it with "conda update jupuyterlab" - It says everything is already up-to-date
I tried with "conda update -c conda-forge jupyterlab" - It updated it but the bug is still here

**Comment by fabioanza** [comment]
Hey, I uninstalled and installed it back twice. The second time it worked. Don't know what to tell you.
Thank you for you help anyway!!
