### ISSUE TITLE
Extensions are both uninstalled and enabled?

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab#8449]
## Description

I am hunting for a bug that I believe is related to an extensions, but I don't know which (I'm getting frequent ZombieProcess Errors in the console).

So, I used the built-in extension manager to uninstall all extensions.  After the rebuild that went without errors, I now seem to have the curious state that these extensions are both uninstalled but also enabled and OK? I really don't know what is going on or what this means:
<img width="593" alt="Screenshot 2020-05-20 10 23 59" src="https://user-images.githubusercontent.com/69774/82471536-09dc1400-9a84-11ea-8eb9-199f863b11df.png">

## Reproduce

1. Install extensions via built-in extension manager
2. Rebuild
3. Remove extensions via built-in extension manager
4. Rebuild
5. List installed extensions either via built-in extension manager or "jupyter labextension list"

## Expected behavior

I expect uninstalling extensions to make extensions disappear and not be enabled.

## Context

- Operating System and version: macOS 10.14.6
- Browser and version: Safari 13.04
- JupyterLab version: 2.1.2

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/Users/klay6683/miniconda3/condabin
	/Users/klay6683/miniconda3/envs/py38/bin
	/Users/klay6683/miniconda3/condabin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/opt/X11/bin
	/Library/TeX/texbin
	.
	/usr/local/sbin
	/Users/klay6683/bin
	/Users/klay6683/.local/bin
	/Users/klay6683/.poetry/bin

sys.path:
	/Users/klay6683/miniconda3/envs/py38/bin
	/Users/klay6683/miniconda3/envs/py38/lib/python38.zip
	/Users/klay6683/miniconda3/envs/py38/lib/python3.8
	/Users/klay6683/miniconda3/envs/py38/lib/python3.8/lib-dynload
	/Users/klay6683/miniconda3/envs/py38/lib/python3.8/site-packages
	/Users/klay6683/Dropbox/src/planetarypy

sys.executable:
	/Users/klay6683/miniconda3/envs/py38/bin/python

sys.version:
	3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
	[Clang 9.0.1 ]

platform.platform():
	macOS-10.14.6-x86_64-i386-64bit

which -a jupyter:
	/Users/klay6683/miniconda3/envs/py38/bin/jupyter

pip list:
	Package                           Version             Location
	--------------------------------- ------------------- ---------------------------------------
	affine                            2.3.0
	aiohttp                           3.6.2
	alabaster                         0.7.12
	apipkg                            1.5
	appdirs                           1.4.3
	appnope                           0.1.0
	argh                              0.26.2
	astroid                           2.4.1
	astropy                           4.0.1.post1
	async-timeout                     3.0.1
	attrs                             19.3.0
	autopep8                          1.5.2
	Babel                             2.8.0
	backcall                          0.1.0
	basemap                           1.2.1
	black                             19.10b0
	bleach                            3.1.5
	bokeh                             2.0.1
	brotlipy                          0.7.0
	bump2version                      1.0.0
	Cartopy                           0.18.0
	certifi                           2020.4.5.1
	cffi                              1.14.0
	cftime                            1.1.3
	chardet                           3.0.4
	click                             7.1.2
	click-plugins                     1.1.1
	cligj                             0.5.0
	cloudpickle                       1.4.1
	cmarkgfm                          0.4.2
	colorama                          0.4.3
	colorcet                          2.0.1
	coverage                          5.1
	cryptography                      2.9.2
	cycler                            0.10.0
	Cython                            0.29.18
	cytoolz                           0.10.1
	dask                              2.16.0
	dask-labextension                 2.0.2
	datashader                        0.10.0
	datashape                         0.5.4
	decorator                         4.4.2
	defusedxml                        0.6.0
	distributed                       2.16.0
	docutils                          0.16
	entrypoints                       0.3
	execnet                           1.7.1
	fastparquet                       0.4.0
	Fiona                             1.8.13
	flake8                            3.8.1
	fsspec                            0.7.3
	future                            0.18.2
	GDAL                              3.0.4
	geopandas                         0.7.0
	geoviews                          1.8.1
	gitdb                             4.0.5
	GitPython                         3.1.2
	graphviz                          0.14
	h5py                              2.10.0
	HeapDict                          1.0.1
	holoviews                         1.13.2
	hvplot                            0.5.2
	idna                              2.9
	imagecodecs-lite                  2019.12.3
	imageio                           2.8.0
	imagesize                         1.2.0
	importlib-metadata                1.6.0
	importlib-resources               1.5.0
	intake                            0.5.5
	ipykernel                         5.2.1
	ipympl                            0.5.6
	ipyparallel                       6.3.0
	ipython                           7.14.0
	ipython-genutils                  0.2.0
	ipywidgets                        7.5.1
	isort                             4.3.21
	jedi                              0.17.0
	Jinja2                            2.11.2
	joblib                            0.15.1
	json5                             0.9.0
	jsonschema                        3.2.0
	jupyter-client                    6.1.3
	jupyter-contrib-core              0.3.3
	jupyter-core                      4.6.3
	jupyter-nbextensions-configurator 0.4.1
	jupyter-server-proxy              1.4.0
	jupyterlab                        2.1.2
	jupyterlab-code-formatter         1.3.1
	jupyterlab-git                    0.20.0
	jupyterlab-github                 2.0.0
	jupyterlab-server                 1.1.4
	keyring                           21.2.1
	kiwisolver                        1.2.0
	latexcodec                        2.0.0
	lazy-object-proxy                 1.4.3
	livereload                        2.6.1
	llvmlite                          0.31.0
	locket                            0.2.0
	lxml                              4.5.1
	Markdown                          3.2.2
	MarkupSafe                        1.1.1
	matplotlib                        3.2.1
	mccabe                            0.6.1
	mistune                           0.8.4
	mock                              4.0.2
	more-itertools                    8.3.0
	msgpack                           1.0.0
	multidict                         4.7.5
	multipledispatch                  0.6.0
	munch                             2.5.0
	mypy                              0.770
	mypy-extensions                   0.4.3
	nb-conda-kernels                  2.2.3
	nbconvert                         5.6.1
	nbdime                            2.0.0
	nbformat                          5.0.6
	nbresuse                          0.3.3
	nbsphinx                          0.7.0
	nbstripout                        0.3.7
	nbval                             0.9.5
	netCDF4                           1.5.3
	networkx                          2.4
	notebook                          6.0.3
	numba                             0.48.0
	numexpr                           2.7.1
	numpy                             1.18.4
	olefile                           0.46
	oset                              0.1.3
	OWSLib                            0.19.2
	packaging                         20.4
	pandas                            1.0.3
	pandocfilters                     1.4.2
	panel                             0.9.5
	param                             1.9.3
	parso                             0.7.0
	partd                             1.1.0
	pathspec                          0.8.0
	pathtools                         0.1.2
	patsy                             0.5.1
	pep8                              1.7.1
	pexpect                           4.8.0
	pickleshare                       0.7.5
	Pillow                            7.1.2
	pip                               20.1.1
	pkginfo                           1.5.0.1
	planetarypy                       0.5.1               /Users/klay6683/Dropbox/src/planetarypy
	pluggy                            0.13.1
	prometheus-client                 0.7.1
	prompt-toolkit                    3.0.5
	psutil                            5.7.0
	ptyprocess                        0.6.0
	pvl                               0.3.0
	py                                1.8.1
	pyaml                             19.4.1
	pyarrow                           0.17.1
	pybtex                            0.22.2
	pybtex-docutils                   0.2.2
	pycodestyle                       2.6.0
	pycparser                         2.20
	pyct                              0.4.6
	pyepsg                            0.4.0
	pyflakes                          2.2.0
	Pygments                          2.6.1
	pylint                            2.5.2
	pyOpenSSL                         19.1.0
	pyparsing                         2.4.7
	pyproj                            2.6.1.post1
	pyrsistent                        0.16.0
	pyshp                             2.1.0
	PySocks                           1.7.1
	pytest                            5.4.2
	pytest-cache                      1.0
	pytest-cov                        2.8.1
	pytest-pep8                       1.0.6
	python-dateutil                   2.8.1
	python-geotiepoints               1.1.8
	python-pptx                       0.6.18
	python-snappy                     0.5.4
	pytz                              2020.1
	pyviz-comms                       0.7.4
	PyWavelets                        1.1.1
	PyYAML                            5.3.1
	pyzmq                             19.0.1
	rasterio                          1.1.4
	readme-renderer                   24.0
	regex                             2020.5.14
	requests                          2.23.0
	requests-toolbelt                 0.9.1
	requirements-parser               0.2.0
	rise                              5.6.1
	Rtree                             0.9.4
	scikit-image                      0.17.2
	scikit-learn                      0.23.1
	scipy                             1.4.1
	seaborn                           0.10.1
	selenium                          3.141.0
	Send2Trash                        1.5.0
	setuptools                        46.4.0.post20200518
	Shapely                           1.7.0
	simpervisor                       0.3
	six                               1.14.0
	smmap                             3.0.4
	snowballstemmer                   2.0.0
	snuggs                            1.4.7
	sortedcontainers                  2.1.0
	Sphinx                            3.0.3
	sphinxcontrib-applehelp           1.0.2
	sphinxcontrib-bibtex              1.0.0
	sphinxcontrib-devhelp             1.0.2
	sphinxcontrib-htmlhelp            1.0.3
	sphinxcontrib-jsmath              1.0.1
	sphinxcontrib-qthelp              1.0.3
	sphinxcontrib-serializinghtml     1.1.4
	spiceypy                          3.0.2
	statsmodels                       0.11.1
	tables                            3.6.1
	tblib                             1.6.0
	terminado                         0.8.3
	testpath                          0.4.4
	threadpoolctl                     2.0.0
	thrift                            0.11.0
	tifffile                          2020.5.11
	toml                              0.10.1
	toolz                             0.10.0
	tornado                           6.0.4
	tqdm                              4.46.0
	traitlets                         4.3.3
	twine                             3.1.1
	typed-ast                         1.4.1
	typing-extensions                 3.7.4.2
	urllib3                           1.25.9
	watchdog                          0.10.2
	wcwidth                           0.1.9
	webencodings                      0.5.1
	wheel                             0.34.2
	widgetsnbextension                3.5.1
	wrapt                             1.11.2
	xarray                            0.15.1
	xlrd                              1.2.0
	XlsxWriter                        1.2.8
	xlwt                              1.3.0
	yapf                              0.29.0
	yarl                              1.4.2
	zict                              2.0.0
	zipp                              3.1.0

conda list:
	# packages in environment at /Users/klay6683/miniconda3/envs/py38:
	#
	# Name                    Version                   Build  Channel
	abseil-cpp                20200225.2           h4a8c4bd_0    conda-forge
	affine                    2.3.0                      py_0    conda-forge
	aiohttp                   3.6.2                    pypi_0    pypi
	alabaster                 0.7.12                     py_0    conda-forge
	apipkg                    1.5                        py_0    conda-forge
	appdirs                   1.4.3                      py_1    conda-forge
	appnope                   0.1.0           py38h32f6830_1001    conda-forge
	argh                      0.26.2                py38_1001    conda-forge
	arrow-cpp                 0.17.1          py38h8f06d31_2_cpu    conda-forge
	astroid                   2.4.1            py38h32f6830_0    conda-forge
	astropy                   4.0.1.post1      py38h64e0658_0    conda-forge
	async-timeout             3.0.1                    pypi_0    pypi
	attrs                     19.3.0                     py_0    conda-forge
	autopep8                  1.5.2              pyh9f0ad1d_0    conda-forge
	aws-sdk-cpp               1.7.164              h5c602de_1    conda-forge
	babel                     2.8.0                      py_0    conda-forge
	backcall                  0.1.0                      py_0    conda-forge
	basemap                   1.3.0            py38h9bcff04_2    conda-forge
	black                     19.10b0                  py38_0    conda-forge
	bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
	blosc                     1.18.1               h4a8c4bd_0    conda-forge
	bokeh                     2.0.1            py38h32f6830_0    conda-forge
	boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
	brotli                    1.0.7             h4a8c4bd_1001    conda-forge
	brotlipy                  0.7.0           py38h64e0658_1000    conda-forge
	bump2version              1.0.0              pyh9f0ad1d_0    conda-forge
	bzip2                     1.0.8                h0b31af3_2    conda-forge
	c-ares                    1.15.0            h01d97ff_1001    conda-forge
	ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
	cairo                     1.16.0            hec6a9b0_1003    conda-forge
	cartopy                   0.18.0           py38h9f7df5a_0    conda-forge
	certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
	cffi                      1.14.0           py38h356ff06_0    conda-forge
	cfitsio                   3.470                hddc9c06_5    conda-forge
	cftime                    1.1.3            py38h65ad66c_0    conda-forge
	chardet                   3.0.4           py38h32f6830_1006    conda-forge
	click                     7.1.2              pyh9f0ad1d_0    conda-forge
	click-plugins             1.1.1                      py_0    conda-forge
	cligj                     0.5.0                      py_0    conda-forge
	cloudpickle               1.4.1                      py_0    conda-forge
	cmarkgfm                  0.4.2            py38h0b31af3_2    conda-forge
	colorama                  0.4.3                      py_0    conda-forge
	colorcet                  2.0.1                      py_0    conda-forge
	coverage                  5.1              py38h64e0658_0    conda-forge
	cryptography              2.9.2            py38hb761dab_0    conda-forge
	cspice                    66                h0b31af3_1007    conda-forge
	curl                      7.69.1               h2d98d24_0    conda-forge
	cycler                    0.10.0                     py_2    conda-forge
	cython                    0.29.18          py38hc84c608_0    conda-forge
	cytoolz                   0.10.1           py38h0b31af3_0    conda-forge
	dask                      2.16.0                     py_0    conda-forge
	dask-core                 2.16.0                     py_0    conda-forge
	dask-labextension         2.0.2                    pypi_0    pypi
	datashader                0.10.0                     py_0    conda-forge
	datashape                 0.5.4                      py_1    conda-forge
	decorator                 4.4.2                      py_0    conda-forge
	defusedxml                0.6.0                      py_0    conda-forge
	distributed               2.16.0           py38h32f6830_0    conda-forge
	docutils                  0.16             py38h32f6830_1    conda-forge
	entrypoints               0.3             py38h32f6830_1001    conda-forge
	execnet                   1.7.1                      py_0    conda-forge
	expat                     2.2.9                h4a8c4bd_2    conda-forge
	fastparquet               0.4.0            py38h65ad66c_0    conda-forge
	fiona                     1.8.13           py38he71f6a4_0    conda-forge
	flake8                    3.8.1              pyh9f0ad1d_0    conda-forge
	fontconfig                2.13.1            h6b1039f_1001    conda-forge
	freetype                  2.10.2               h8da9a1a_0    conda-forge
	freexl                    1.0.5             h1de35cc_1002    conda-forge
	fsspec                    0.7.3                      py_0    conda-forge
	future                    0.18.2           py38h32f6830_1    conda-forge
	gdal                      3.0.4            py38h9f7df5a_6    conda-forge
	geopandas                 0.7.0                      py_1    conda-forge
	geos                      3.8.1                h4a8c4bd_0    conda-forge
	geotiff                   1.5.1               hd8796ba_10    conda-forge
	geoviews                  1.8.1                      py_0    conda-forge
	geoviews-core             1.8.1                      py_0    conda-forge
	gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
	gflags                    2.2.2             h4a8c4bd_1002    conda-forge
	giflib                    5.2.1                h0b31af3_2    conda-forge
	gitdb                     4.0.5                      py_0    conda-forge
	gitpython                 3.1.2                      py_0    conda-forge
	glib                      2.64.2               h577aef8_1    conda-forge
	glog                      0.4.0                h700f914_3    conda-forge
	graphviz                  2.42.3               h98dfb87_0    conda-forge
	grpc-cpp                  1.29.0               h0284957_0    conda-forge
	h5py                      2.10.0          nompi_py38h106b333_102    conda-forge
	hdf4                      4.2.13            h84186c3_1003    conda-forge
	hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
	heapdict                  1.0.1                      py_0    conda-forge
	holoviews                 1.13.2             pyh9f0ad1d_0    conda-forge
	hvplot                    0.5.2                      py_0    conda-forge
	icu                       64.2                 h6de7cb9_1    conda-forge
	idna                      2.9                        py_1    conda-forge
	imagecodecs-lite          2019.12.3        py38h64e0658_0    conda-forge
	imageio                   2.8.0                      py_0    conda-forge
	imagesize                 1.2.0                      py_0    conda-forge
	importlib-metadata        1.6.0            py38h32f6830_0    conda-forge
	importlib-resources       1.5.0                    pypi_0    pypi
	importlib_metadata        1.6.0                         0    conda-forge
	intake                    0.5.5                      py_0    conda-forge
	ipykernel                 5.2.1            py38h23f93f0_0    conda-forge
	ipympl                    0.5.6              pyh9f0ad1d_1    conda-forge
	ipyparallel               6.3.0            py38h32f6830_0    conda-forge
	ipython                   7.14.0           py38h32f6830_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	ipywidgets                7.5.1                      py_0    conda-forge
	isort                     4.3.21           py38h32f6830_1    conda-forge
	jedi                      0.17.0           py38h32f6830_0    conda-forge
	jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
	joblib                    0.15.1                     py_0    conda-forge
	jpeg                      9c                h1de35cc_1001    conda-forge
	json-c                    0.13.1            h575e443_1002    conda-forge
	json5                     0.9.0                      py_0    conda-forge
	jsonschema                3.2.0            py38h32f6830_1    conda-forge
	jupyter-server-proxy      1.4.0                    pypi_0    pypi
	jupyter_client            6.1.3                      py_0    conda-forge
	jupyter_contrib_core      0.3.3                      py_2    conda-forge
	jupyter_core              4.6.3            py38h32f6830_1    conda-forge
	jupyter_nbextensions_configurator 0.4.1                    py38_0    conda-forge
	jupyterlab                2.1.2                      py_0    conda-forge
	jupyterlab-git            0.20.0                     py_0    conda-forge
	jupyterlab-github         2.0.0                    pypi_0    pypi
	jupyterlab_code_formatter 1.3.1                      py_0    conda-forge
	jupyterlab_server         1.1.4                      py_0    conda-forge
	kealib                    1.4.13               h2324030_0    conda-forge
	keyring                   21.2.1           py38h32f6830_0    conda-forge
	kiwisolver                1.2.0            py38ha0d09dd_0    conda-forge
	krb5                      1.17.1               h1752a42_0    conda-forge
	latexcodec                2.0.0                      py_0    conda-forge
	lazy-object-proxy         1.4.3            py38h64e0658_2    conda-forge
	libblas                   3.8.0               16_openblas    conda-forge
	libcblas                  3.8.0               16_openblas    conda-forge
	libcurl                   7.69.1               hc0b9707_0    conda-forge
	libcxx                    10.0.0               h1af66ff_2    conda-forge
	libdap4                   3.20.6               h8c15375_0    conda-forge
	libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
	libevent                  2.1.10               hafa8578_0    conda-forge
	libffi                    3.2.1             h4a8c4bd_1007    conda-forge
	libgdal                   3.0.4                ha92c1e4_6    conda-forge
	libgfortran               4.0.0                         2    conda-forge
	libiconv                  1.15              h0b31af3_1006    conda-forge
	libkml                    1.3.0             h169b8f9_1011    conda-forge
	liblapack                 3.8.0               16_openblas    conda-forge
	libllvm8                  8.0.1                h770b8ee_0    conda-forge
	libnetcdf                 4.7.4           nompi_he461dc0_101    conda-forge
	libopenblas               0.3.9                h3d69b6c_0    conda-forge
	libpng                    1.6.37               hbbe82c9_1    conda-forge
	libpq                     12.2                 h489d428_1    conda-forge
	libprotobuf               3.11.4               hd174df1_0    conda-forge
	libsodium                 1.0.17               h01d97ff_0    conda-forge
	libspatialindex           1.9.3                h4a8c4bd_3    conda-forge
	libspatialite             4.3.0a            h658e6c1_1038    conda-forge
	libssh2                   1.9.0                h39bdce6_2    conda-forge
	libtiff                   4.1.0                h2ae36a8_6    conda-forge
	libuv                     1.34.0               h0b31af3_0    conda-forge
	libwebp-base              1.1.0                h0b31af3_3    conda-forge
	libxml2                   2.9.10               h53d96d6_0    conda-forge
	libxslt                   1.1.33               h320ff13_0    conda-forge
	livereload                2.6.1                      py_0    conda-forge
	llvm-openmp               10.0.0               h28b9765_0    conda-forge
	llvmlite                  0.31.0           py38h0d43c1d_1    conda-forge
	locket                    0.2.0                      py_2    conda-forge
	lxml                      4.5.1            py38hc829089_0    conda-forge
	lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
	markdown                  3.2.2                      py_0    conda-forge
	markupsafe                1.1.1            py38h64e0658_1    conda-forge
	matplotlib-base           3.2.1            py38h1300a51_0    conda-forge
	mccabe                    0.6.1                      py_1    conda-forge
	mistune                   0.8.4           py38h64e0658_1001    conda-forge
	mock                      4.0.2            py38h32f6830_0    conda-forge
	more-itertools            8.3.0                      py_0    conda-forge
	msgpack-python            1.0.0            py38ha0d09dd_1    conda-forge
	multidict                 4.7.5            py38h64e0658_1    conda-forge
	multipledispatch          0.6.0                      py_0    conda-forge
	munch                     2.5.0                      py_0    conda-forge
	mypy                      0.770                      py_0    conda-forge
	mypy_extensions           0.4.3            py38h32f6830_1    conda-forge
	nb_conda_kernels          2.2.3                    py38_0    conda-forge
	nbconvert                 5.6.1            py38h32f6830_1    conda-forge
	nbdime                    2.0.0                      py_1    conda-forge
	nbformat                  5.0.6                      py_0    conda-forge
	nbresuse                  0.3.3                      py_0    conda-forge
	nbsphinx                  0.7.0              pyh9f0ad1d_0    conda-forge
	nbstripout                0.3.7                      py_0    conda-forge
	nbval                     0.9.5                      py_0    conda-forge
	ncurses                   6.1               h0a44026_1002    conda-forge
	netcdf4                   1.5.3           nompi_py38h645dd01_103    conda-forge
	networkx                  2.4                        py_1    conda-forge
	nodejs                    13.13.0              h38d8c5a_0    conda-forge
	notebook                  6.0.3            py38h32f6830_0    conda-forge
	numba                     0.48.0           py38h4f17bb1_0    conda-forge
	numexpr                   2.7.1            py38h5fc983b_1    conda-forge
	numpy                     1.18.4           py38h1f821a2_0    conda-forge
	olefile                   0.46                       py_0    conda-forge
	openjpeg                  2.3.1                h254dc36_3    conda-forge
	openssl                   1.1.1g               h0b31af3_0    conda-forge
	oset                      0.1.3                      py_1    conda-forge
	owslib                    0.19.2                     py_1    conda-forge
	packaging                 20.4               pyh9f0ad1d_0    conda-forge
	pandas                    1.0.3            py38h5fc983b_1    conda-forge
	pandoc                    2.9.2.1                       0    conda-forge
	pandocfilters             1.4.2                      py_1    conda-forge
	panel                     0.9.5                      py_1    conda-forge
	param                     1.9.3                      py_0    conda-forge
	parquet-cpp               1.5.1                         2    conda-forge
	parso                     0.7.0              pyh9f0ad1d_0    conda-forge
	partd                     1.1.0                      py_0    conda-forge
	pathspec                  0.8.0              pyh9f0ad1d_0    conda-forge
	pathtools                 0.1.2                      py_1    conda-forge
	patsy                     0.5.1                      py_0    conda-forge
	pcre                      8.44                 h4a8c4bd_0    conda-forge
	pep8                      1.7.1                      py_0    conda-forge
	pexpect                   4.8.0            py38h32f6830_1    conda-forge
	phantomjs                 2.1.1                         1    conda-forge
	pickleshare               0.7.5           py38h32f6830_1001    conda-forge
	pillow                    7.1.2            py38h83dc5e5_0    conda-forge
	pip                       20.1.1             pyh9f0ad1d_0    conda-forge
	pixman                    0.38.0            h01d97ff_1003    conda-forge
	pkginfo                   1.5.0.1                    py_0    conda-forge
	planetarypy               0.5.1                     dev_0    <develop>
	pluggy                    0.13.1           py38h32f6830_1    conda-forge
	poppler                   0.67.0               h16886b5_8    conda-forge
	poppler-data              0.4.9                         1    conda-forge
	postgresql                12.2                 h62ab893_1    conda-forge
	proj                      7.0.0                hbce2d5c_4    conda-forge
	prometheus_client         0.7.1                      py_0    conda-forge
	prompt-toolkit            3.0.5                      py_0    conda-forge
	psutil                    5.7.0            py38h64e0658_1    conda-forge
	ptyprocess                0.6.0                   py_1001    conda-forge
	pvl                       0.3.0                      py_1    conda-forge
	py                        1.8.1                      py_0    conda-forge
	pyaml                     19.4.1                     py_0    conda-forge
	pyarrow                   0.17.1           py38hb42247f_0    conda-forge
	pybtex                    0.22.2           py38h32f6830_1    conda-forge
	pybtex-docutils           0.2.2            py38h32f6830_1    conda-forge
	pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
	pycparser                 2.20                       py_0    conda-forge
	pyct                      0.4.6                      py_0    conda-forge
	pyct-core                 0.4.6                      py_0    conda-forge
	pyepsg                    0.4.0                      py_0    conda-forge
	pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
	pygments                  2.6.1                      py_0    conda-forge
	pylint                    2.5.2            py38h32f6830_0    conda-forge
	pyopenssl                 19.1.0                     py_1    conda-forge
	pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
	pyproj                    2.6.1.post1      py38h7d7e87d_0    conda-forge
	pyrsistent                0.16.0           py38h64e0658_0    conda-forge
	pyshp                     2.1.0                      py_0    conda-forge
	pysocks                   1.7.1            py38h32f6830_1    conda-forge
	pytables                  3.6.1            py38h6f8395a_1    conda-forge
	pytest                    5.4.2            py38h32f6830_0    conda-forge
	pytest-cache              1.0                        py_2    conda-forge
	pytest-cov                2.8.1                      py_0    conda-forge
	pytest-pep8               1.0.6                      py_2    conda-forge
	python                    3.8.2           hd5f0129_7_cpython    conda-forge
	python-dateutil           2.8.1                      py_0    conda-forge
	python-geotiepoints       1.1.8            py38h3b54f70_0    conda-forge
	python-graphviz           0.14               pyh9f0ad1d_0    conda-forge
	python-pptx               0.6.18                     py_0    conda-forge
	python-snappy             0.5.4            py38hae8407a_1    conda-forge
	python_abi                3.8                      1_cp38    conda-forge
	pytz                      2020.1             pyh9f0ad1d_0    conda-forge
	pyviz_comms               0.7.4              pyh8c360ce_0    conda-forge
	pywavelets                1.1.1            py38h65ad66c_1    conda-forge
	pyyaml                    5.3.1            py38h64e0658_0    conda-forge
	pyzmq                     19.0.1           py38h1fcdcd6_0    conda-forge
	rasterio                  1.1.4            py38hc9271d6_0    conda-forge
	re2                       2020.05.01           h4a8c4bd_1    conda-forge
	readline                  8.0                  hcfe32e1_0    conda-forge
	readme_renderer           24.0                       py_0    conda-forge
	regex                     2020.5.14        py38h64e0658_0    conda-forge
	requests                  2.23.0             pyh8c360ce_2    conda-forge
	requests-toolbelt         0.9.1                      py_0    conda-forge
	requirements-parser       0.2.0                      py_0    conda-forge
	rise                      5.6.1                    py38_0    conda-forge
	rtree                     0.9.4            py38h08f867b_1    conda-forge
	scikit-image              0.17.2           py38h5fc983b_0    conda-forge
	scikit-learn              0.23.1           py38hb7f0800_0    conda-forge
	scipy                     1.4.1            py38h38b60c6_3    conda-forge
	seaborn                   0.10.1                     py_0    conda-forge
	selenium                  3.141.0         py38h64e0658_1001    conda-forge
	send2trash                1.5.0                      py_0    conda-forge
	setuptools                46.4.0           py38h32f6830_0    conda-forge
	shapely                   1.7.0            py38h5b1fbde_3    conda-forge
	simpervisor               0.3                      pypi_0    pypi
	six                       1.14.0                     py_1    conda-forge
	smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
	snappy                    1.1.8                h4a8c4bd_1    conda-forge
	snowballstemmer           2.0.0                      py_0    conda-forge
	snuggs                    1.4.7                      py_0    conda-forge
	sortedcontainers          2.1.0                      py_0    conda-forge
	sphinx                    3.0.3                      py_0    conda-forge
	sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
	sphinxcontrib-bibtex      1.0.0                      py_0    conda-forge
	sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
	sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
	sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
	sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
	sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
	spiceypy                  3.0.2                      py_0    conda-forge
	sqlite                    3.30.1               h93121df_0    conda-forge
	statsmodels               0.11.1           py38h64e0658_1    conda-forge
	tbb                       2018.0.5             h04f5b5a_0  
	tblib                     1.6.0                      py_0    conda-forge
	terminado                 0.8.3            py38h32f6830_1    conda-forge
	testpath                  0.4.4                      py_0    conda-forge
	threadpoolctl             2.0.0              pyh5ca1d4c_0    conda-forge
	thrift                    0.11.0          py38h4a8c4bd_1001    conda-forge
	thrift-cpp                0.13.0               h0a7acf3_2    conda-forge
	tifffile                  2020.5.11                  py_0    conda-forge
	tiledb                    1.7.7                h84aa2a7_1    conda-forge
	tk                        8.6.10               hbbe82c9_0    conda-forge
	toml                      0.10.1             pyh9f0ad1d_0    conda-forge
	toolz                     0.10.0                     py_0    conda-forge
	tornado                   6.0.4            py38h64e0658_1    conda-forge
	tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
	traitlets                 4.3.3            py38h32f6830_1    conda-forge
	twine                     3.1.1                    py38_0    conda-forge
	typed-ast                 1.4.1            py38h0b31af3_0    conda-forge
	typing_extensions         3.7.4.2                    py_0    conda-forge
	tzcode                    2020a                h0b31af3_0    conda-forge
	urllib3                   1.25.9                     py_0    conda-forge
	watchdog                  0.10.2           py38h0b31af3_0    conda-forge
	wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	wheel                     0.34.2                     py_1    conda-forge
	widgetsnbextension        3.5.1                    py38_0    conda-forge
	wrapt                     1.11.2           py38h64e0658_0    conda-forge
	xarray                    0.15.1                     py_0    conda-forge
	xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
	xlrd                      1.2.0                      py_0    conda-forge
	xlsxwriter                1.2.8                      py_0    conda-forge
	xlwt                      1.3.0                      py_1    conda-forge
	xz                        5.2.5                h0b31af3_0    conda-forge
	yaml                      0.2.4                h0b31af3_0    conda-forge
	yapf                      0.29.0                     py_0    conda-forge
	yarl                      1.4.2                    pypi_0    pypi
	zeromq                    4.3.2                h6de7cb9_2    conda-forge
	zict                      2.0.0                      py_0    conda-forge
	zipp                      3.1.0                      py_0    conda-forge
	zlib                      1.2.11            h0b31af3_1006    conda-forge
	zstd                      1.4.4                h4b3e974_3    conda-forge
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
[Warning] Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details. (vendors~main.64b4c9e7a6bec32cee04.js, line 157730)

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: CollapsibleSection
[Log] Starting WebSocket: wss://localhost:8902/api/kernels/78c03e6e-6ad7-4cc4-808b-e488c09bf68d (vendors~main.64b4c9e7a6bec32cee04.js, line 144046)
[Log] Starting WebSocket: wss://localhost:8902/api/kernels/78c03e6e-6ad7-4cc4-808b-e488c09bf68d (vendors~main.64b4c9e7a6bec32cee04.js, line 144046)
[Error] Error: Kernel connection is disposed
_errorIfDisposed — default.js:1177
_assertCurrentMessage — default.js:964
(anonymous function) — default.js:1088
asyncFunctionResume
[native code]
promiseReactionJob

	(anonymous function) (vendors~main.64b4c9e7a6bec32cee04.js:144095)
	promiseReactionJob</pre>
</details>
Note, interestingly, I do not get the "Kernel is disposed" error in Brave (Chrome-based browser).

**Comment by blink1073** [comment]
This does indeed look like a bug, those extensions were mis-labeled as core extensions.

**Comment by krassowski** [comment]
This seems to be a common problem related to #8122 (or is it exactly the same?). Many users have reported this. A potentially related workaround was described on [Jupyter discourse](https://discourse.jupyter.org/t/extension-shows-up-as-both-installed-and-uninstalled-and-doesnt-work/2688).

**Comment by blink1073** [comment]
I just released 2.1.4.  I agree that should fix this bug.

**Comment by michaelaye** [comment]
Sure this is fixed?

I am unfortunately not sure, if I uninstalled google drive extension before updating to 2.1.4.
In any case, what's my remedy?

```bash
$ jupyter labextension list                                                               (py37)
JupyterLab v2.1.4
Known labextensions:
   app dir: /Users/klay6683/miniconda3/envs/py37/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/geojson-extension v2.0.1  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/github v2.0.0  enabled  OK
        @jupyterlab/google-drive v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v1.0.4  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

Uninstalled core extensions:
    @jupyterlab/google-drive
```

**Comment by michaelaye** [comment]
Don't think that's fixed yet. I just removed jupyterlab-git with 2.1.4 and it shows the exact same behavior.

Also, while the extension manager kicked out google drive from the list without suggesting a re-build, after doing that the `labextension list` still lists it:

```bash
$ jupyter labextension list                                                                  (py37)
JupyterLab v2.1.4
Known labextensions:
   app dir: /Users/klay6683/miniconda3/envs/py37/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/geojson-extension v2.0.1  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/github v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v1.0.4  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.1  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

Uninstalled core extensions:
    @jupyterlab/git
    @jupyterlab/google-drive
```

**Comment by blink1073** [comment]
I think you may still have a `<app_dir>/settings/build_config.json` hanging around with the metadata.  You can find `app_dir` from `jupyter lab paths`.

**Comment by michaelaye** [comment]
this is still happening on freshly set up computers (in June!):

```
$ jupyter labextension list                                                                       (py37) 
JupyterLab v2.1.5
Known labextensions:
   app dir: /home/maye/miniconda3/envs/py37/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.2  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/geojson-extension v2.0.1  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/github v2.0.0  enabled  OK
        @jupyterlab/katex-extension v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @krassowski/jupyterlab_go_to_definition v1.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v1.0.4  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.1  enabled  OK
        dask-labextension v2.0.2  enabled  OK
        jupyter-leaflet v0.13.0  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        jupyter-threejs v2.2.0  enabled  OK
        jupyterlab-datawidgets v6.2.0  enabled  OK
        jupyterlab-plotly v4.8.2  enabled  OK
        jupyterlab-spreadsheet v0.3.2  enabled  OK
        jupyterlab-theme-solarized-dark v1.0.1  enabled  OK
        jupyterlab-theme-toggle v0.5.0  enabled  OK
        jupyterlab_conda v2.1.2 disabled OK

Uninstalled core extensions:
    jupyterlab-theme-toggle
```

**Comment by michaelaye** [comment]
same signature with 2.2.6:

```bash
$ jupyter labextension list                                                                                               (py37) 
JupyterLab v2.2.6
Known labextensions:
   app dir: /home/klay6683/miniconda3/envs/py37/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/geojson-extension v2.0.1  enabled  OK
        @jupyterlab/git v0.20.0  enabled  OK
        @jupyterlab/github v2.0.0  enabled  OK
        @jupyterlab/google-drive v2.0.0  enabled  OK
        @jupyterlab/latex v2.0.1  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        @jupyterlab/statusbar v2.2.1  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK
        @pyviz/jupyterlab_pyviz v1.0.4  enabled  OK
        dask-labextension v3.0.0  enabled  OK
        jupyter-leaflet v0.13.2  enabled  OK
        jupyter-matplotlib v0.7.3  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK

Uninstalled core extensions:
    @jupyterlab/github
    @jupyterlab/google-drive
```

**Comment by thakkarparth007** [comment]
In case someone comes here looking for a solution to extensions not working:

I had tried removing build_config.json and also had tried uninstalling and reinstalling jupyter[lab] several times but nothing worked. What worked in the end was to explicitly enable the serverextension using `jupyter serverextension enable --py <xyz>`.
