### ISSUE TITLE
Sharable links are broken by auto-generated/cloned workspaces

### ISSUE THREAD

**Issue by gerrymanoim** [jupyterlab/jupyterlab#8740]
## Description

I believe this is a regression of https://github.com/jupyterlab/jupyterlab/issues/6772

When shareable links create a new automatically generated workspace, they do not follow `/tree` navigation. 

- See also: https://discourse.jupyter.org/t/url-with-tree-doesnt-work-with-auto-workspace/3729

## Reproduce

I've reproduced this locally and on binder. 

1. Go to https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo
2. Right click `Lorenz.ipynb` and copy sharable link
3. Open a new tab (but keep the old tab open). 
4. Past your sharable link. A new workspace is generated, but navigation to `Lorenz.ipynb` does not occur. 

![image](https://user-images.githubusercontent.com/194147/88835824-d0223a80-d1a3-11ea-8077-8c7162ce3c30.png)

5. If you navigate to the url in your new browser tab (in the auto generated workspace) by hitting enter again, you will now be navigated to the correct notebook. 

Also, if you copy a sharable link and manually create a new workspace, navigation will work as expected. For example, taking the sharable link https://hub.gke.mybinder.org/user/jupyterlab-jupyterlab-demo-k3ld91xb/lab/tree/demo/Lorenz.ipynb and changing it to https://hub.gke.mybinder.org/user/jupyterlab-jupyterlab-demo-k3ld91xb/lab/workspaces/some-random-text/tree/demo/Lorenz.ipynb navigation will work as expected. 

I _believe_ that the problem is redirection does not happen after cloning. https://hub.gke.mybinder.org/user/jupyterlab-jupyterlab-demo-k3ld91xb/lab/workspaces/some-random-text/tree/demo/Lorenz.ipynb?clone will not work. 

## Expected behavior

If sharable links cause a new workspace to be created, jupyterlab will still follow `/tree` navigation to the shared notebook. 

## Context

- Operating System and version: macOS 10.14.16 and binder
- Browser and version: Chrome 84.0.4147.89
- JupyterLab version: 2.1.4 and master (on binder).

**Comment by ellisonbg** [comment]
This may have changed since the new URL handling of single doc mode. I will take a look.

**Comment by ellisonbg** [comment]
We believe this is fixed, please reopen if there are aspects of the problem that remain.

**Comment by DarkmatterVale** [comment]
@ellisonbg 

I've found this bug is still present `2.2.9`. Is the fix you mentioned only going to be available for `3.x`?
